### ISSUE TITLE
Protocol-less URIs are not followed in og:image/image_src meta tag 

### ISSUE THREAD

**Issue by JamesHarrison** [reddit/reddit#1069]
In [this lib](https://github.com/reddit/reddit/blob/master/r2/r2/lib/media.py#L170) the call to `urllib2.urlopen` will fail if the URI provided (eg by the og:image meta tag or image_src link tag) is not protocol-specific - that is, it is a URI of the form `//some-host/path` (as opposed to `http://some-host/path`).

It might be best to check for presence of `http:` in the string and prepend it, as a very simple approach - but the main use case for protocol-less URIs is for pages that support HTTPS, where an alternate domain is used but the protocol should follow that used to retrieve the upstream document; this behavior could be implemented.

As it is, such image_src/og:image links will fail to be loaded by the site as thumbnails.

**Comment by xiongchiamiov** [comment]
Fixed with f755995.  Thanks for the report!
