### ISSUE TITLE
reddit.com/.compact doesn't show the submissions' points when you scroll down

### ISSUE THREAD

**Issue by MaTachi** [reddit/reddit#1114]
The posts that are loaded when you scroll down on <http://www.reddit.com/.compact> don't have visible point counters.

1. Open <http://www.reddit.com/.compact>.
2. Scroll down below the initially loaded submissions.
3. The submissions loaded by the ajax are missing points.

This happens in Firefox on Android and Firefox on the Linux desktop. I haven't tried any other browsers.

![screenshot](http://i.imgur.com/T5ACT6o.png)

**Comment by JordanMilne** [comment]
Looks like this was fixed by https://github.com/reddit/reddit/commit/159c51b2b474ed2dafec6724d051445cb395d8a8. IIRC it was something to do with `.json-compact` using a different `score_fmt`.
