### ISSUE TITLE
Server header field is "cloudflare-nginx," not "'; DROP TABLE servertypes; --"

### ISSUE THREAD

**Issue by ehrmann** [reddit/reddit#1117]
The server header seems to have been corrupted. Rather than reporting @jedberg's SQL injection response, it's reporting a generic CDN/nginx one.

**Comment by DaAwesomeP** [comment]
What exactly is `X-moose: majestic`?

**Comment by stuartpb** [comment]
Can we maybe do `X-Powered-By: "'; DROP TABLE frameworks; --"?
