### ISSUE TITLE
domain/ api endpoints undocumented, unsupported by oauth

### ISSUE THREAD

**Issue by damianb** [reddit/reddit#1147]
As on tin. The suite of endpoints provided by `domain/` (e.g. https://reddit.com/domain/google.com/ ) are undocumented and don't seem to be supported by oauth - I'm encountering some errors when trying to access them directly.

**Comment by damianb** [comment]
!

**Comment by damianb** [comment]
For the record, this issue should be addressed before the deprecation of the old API, and OAuth becomes mandated to access the reddit API.

**Comment by kemitche** [comment]
The domain endpoints ARE supported via OAuth; they are listings, requiring "read" scope. If you're seeing "errors" please report them to /r/redditdev with as much info as possible (request/response headers, body, etc.)

They were equally undocumented under the cookie API. It's a limitation of the current way we handle those endpoints and how the documentation is generated for various listings.
