### ISSUE TITLE
Buttons link to redditstatic.com

### ISSUE THREAD

**Issue by ohmanger** [reddit/reddit#1150]
Currently the snoo logo on the buttons will link to redditstatic which gives a 404.

Have a look at:
http://www.redditstatic.com/button/button1.html
http://www.redditstatic.com/button/button2.html
http://www.redditstatic.com/button/button3.html

**Comment by elantrian** [comment]
Seems stale/resolved?

**Comment by ohmanger** [comment]
All good now.
