### ISSUE TITLE
Subreddit recommendation API no longer returning results.

### ISSUE THREAD

**Issue by listentous** [reddit/reddit#1169]
As of about a week ago it only returns an empty [] set.

Ex: http://api.reddit.com/api/recommend/sr/listentous

**Comment by avidw** [comment]
Can we reopen this issue? The recommendation API seems to be returning empty arrays again ([example](https://www.reddit.com/api/recommend/sr/pics?api_type=json)).

**Comment by ialvarez** [comment]
This is still returning empty arrays. Could someone have a look please?
Thanks.

**Comment by listentous** [comment]
Issue reopened.

**Comment by ThorArakis** [comment]
The recommendations are all populated by a (clearly brittle) cron job right now. Looks like it's been failing silently for a while. I fixed it up and recommendations are flowing again. Sorry about the wait.
