### ISSUE TITLE
Submit Reddit Link on postcard gallery to /r/postcards does not work

### ISSUE THREAD

**Issue by johnathanmartin** [reddit/reddit#1236]
On the postcard gallery there are submit widgets on all postcards to submit the postcard to the /r/postcards subreddit. This subreddit can only be submitted by mods/admins and there is no point in having the widget as users can not use it. 

![image](https://cloud.githubusercontent.com/assets/6856083/5703863/6b01e600-9a31-11e4-8d5e-74987ec72b2f.png)

![image](https://cloud.githubusercontent.com/assets/6856083/5703851/4026a11e-9a31-11e4-85ea-b34ca976dca9.png)

Please remove the widget. Thank You.

**Comment by angrypotato1** [comment]
Where is the postcard gallery?

**Comment by xiongchiamiov** [comment]
> Where is the postcard gallery?

https://www.reddit.com/about/postcards/

I *think* this [should be filed](https://github.com/reddit/reddit-plugin-about/blob/master/reddit_about/about.py#L66-L78) over in [the about plugin](https://github.com/reddit/reddit-plugin-about/issues/new).

**Comment by johnathanmartin** [comment]
Thank you, sorry about that. Will file in correct repo. 

Issue Closed
