### ISSUE TITLE
adding a meta tag to open in AlienBlue on iOS

### ISSUE THREAD

**Issue by Haroenv** [reddit/reddit#1240]
the meta tag should be in the html and promoted like this:

    <meta name="apple-itunes-app" content="app-id=myAppStoreID, affiliate-data=myAffiliateData, app-argument=myURL">

[apple document](https://developer.apple.com/library/ios/documentation/AppleApplications/Reference/SafariWebContent/PromotingAppswithAppBanners/PromotingAppswithAppBanners.html)

**Comment by jvbreen1** [comment]
This issue can probably be closed.
