### ISSUE TITLE
Optimize Error Images

### ISSUE THREAD

**Issue by edent** [reddit/reddit#1241]
(Similar to #1082 #1064 #415)

When Reddit cannot deliver a page to a user (due to load or some other problem) it returns an error page.

Those pages contain images which are unoptimised.   For example, https://www.redditstatic.com/trouble-afoot.png is 137,013 Bytes.

By running the error image through [pngquant](http://pngquant.org/) we can reduce the size to 56,213 Bytes. A significant reduction.

This is especially important for users on slow and/or metered Internet connections (usually mobile users).

Here are the two images, one optimised - one not.  Can you tell which is which?
![trouble-afoot](https://cloud.githubusercontent.com/assets/837136/5815111/73c9c276-a08a-11e4-8acf-d053b7da45c7.png)

![trouble-afoot-fs8](https://cloud.githubusercontent.com/assets/837136/5815102/6102f52c-a08a-11e4-9bd3-53aba1e7e75f.png)

**Comment by eganist** [comment]
In fairness, if this is actually a problem for people on metered
connections, it means Reddit is erroring out *entirely too much.*

But I empathize with the spirit of the change.

**Comment by edent** [comment]
I've seen that error several times over the last few days...

**Comment by spladug** [comment]
Thanks, I've opened reddit/error-pages#11 to address this by converting the image to JPEG.

**Comment by spladug** [comment]
The JPEGized version is rolled out. This saves about 92 KiB on the first, un-cached, request to the image.
