### ISSUE TITLE
How the hotness rank implement?

### ISSUE THREAD

**Issue by wingyiu** [reddit/reddit#1242]
I don't mean the rank algorithm. It there some column store the hot for each link, and use the cron to frequently update all row? Or just update when user vote?

**Comment by spladug** [comment]
Yup, the hot score is just updated when users vote.  The only time-component of the score is the birth-date of the submission which doesn't change.  A list of link IDs is kept in sorted order and updated every time the votes happen as well to speed up queries. 

That code for processing votes and storing the lists of IDs is all based in https://github.com/reddit/reddit/blob/master/r2/r2/lib/db/queries.py .

For future reference, this issue tracker is for bugs in the reddit code.  Please feel free to post in [/r/redditdev](https://www.reddit.com/r/redditdev) with questions.
