### ISSUE TITLE
Contradiction in documentation regarding client secrets for user-less authentication

### ISSUE THREAD

**Issue by spencerkohan** [reddit/reddit#1267]
I'm trying to build a mobile application that incorporates some reddit data without requiring a login.  Because it's an installed app, I do not receive a client secret.  However in the documentation, it seems to indicate that this is required for user-less authentication in [this document](http://github.com/reddit/reddit/wiki/OAuth2) under *Application Only OAuth":

> You must supply your OAuth 2 client's credentials via HTTP Basic Auth for this request.  The "user" is the client_id, the "password" is client_secret .

It seems there must be a way to do this on installed apps, because there is a custom grant_type just for installed clients.

**Comment by xiongchiamiov** [comment]
Hi.  To help keep things clean over here, and to get you more exposed to people who can help, questions like this should go over in [/r/redditdev](https://www.reddit.com/r/redditdev).  If you don't find an answer there, feel free to ping us on Freenode's `#reddit-dev`.  Thanks!
