### ISSUE TITLE
Search by time: "This X" should be "Last X"

### ISSUE THREAD

**Issue by eksperimental** [reddit/reddit#1276]
on the search page, it's misleading the title.

https://github.com/reddit/reddit/blob/abf40b7fed8df5272a0c8ed1042aa2fa96e861bb/r2/r2/lib/menus.py#L68
```python
                     # time sort words
                     hour         = _('this hour'),
                     day          = _('today'),
                     week         = _('this week'),
                     month        = _('this month'),
                     year         = _('this year'),
                     all          = _('all time'),
```
It should read: 
* last hour
* last week
* last month
* last year

for example "this year" shows items from 10 months ago (that is not this year)

**Comment by rjrudman** [comment]
Changing it to 'last year' would have the opposite problem you described

**Comment by eksperimental** [comment]
maybe "past year", 
this year, is for sure this current year,
last year people may understand that is either this last one year, or the previous year, and not this one.

i think last is year is better than this year because at least there is a possibilty of understanding what it actaully means, but "this year" absolute doesn't mean that when we are trying to say "this last one year"

eitherwat.. it sounds complicated

**Comment by Brobin** [comment]
This is such a front-facing part of reddit, I'm not sure if they would change it at this point.

**Comment by eksperimental** [comment]
Google Search Tools, has this same feature and solves it by using "Past X"
![past_year](https://cloud.githubusercontent.com/assets/9133420/6713429/c14fa68e-cdc4-11e4-98a0-f86f8e05c75f.png)

**Comment by madbook** [comment]
this has been updated 5f7526bc59a0429ad88fae00fb9ca78fd1afdf96

**Comment by eksperimental** [comment]
:+1:
