### ISSUE TITLE
Thread header unreadable when browsing without images

### ISSUE THREAD

**Issue by zuckel** [reddit/reddit#1279]
When browsing reddit with images turned off, the header bar containing the thread title, thread up/downvote arrows, preview, number of comments and so on collapses so that I can no longer see the title or any of the other information.

It seems the whole #sitetable is obstructed behind some other content. I can not completely investigate this right now.

Please fix the CSS to make the header layout not depend on images. The rest of the page looks fine w/o images, just the header is messed up.

Motivation: I am currently on a really slow network with high latency and packet loss. Other times people are on mobile connections. Browsing with images turned off makes everything a lot faster in these cases if you only browse text subs.

I am currently on FF 35.0.1 on Windows 8.1.

Thanks!

**Comment by xiongchiamiov** [comment]
For people on a low-throughput mobile network, I highly recommend using a native app or [the mobile website](https://i.reddit.com/), which are optimized for such things.

Your situation is a bit different.  You could use the mobile site, but it's not really designed for as large a screen as you probably have.  You could also use [one of the Windows apps community members have made](http://windows.microsoft.com/en-us/windows/search#q=reddit&s=Store), although I have absolutely no idea how suited they are for desktop usage.

Anyways, this tracker is only for confirmed issues with the codebase, and the functionality of the site with a core browser feature disabled is a bit out of that definition.  I'd recommend you post a thread in [/r/ideasfortheadmins](https://www.reddit.com/r/ideasfortheadmins) to further discuss this.  Thanks!
