### ISSUE TITLE
Error in HTML template

### ISSUE THREAD

**Issue by Dumbaz** [reddit/reddit#1280]
Recieved this message/window when trying to upvote a comment without being logged in:

Du musst angemeldet sein um Sachen Nomen: Aufwertung Verb: Abwertung
Translation: (You have to be logged in to noun: Upvote verb: Downvote (things))

![Image of whole Window](http://puu.sh/gywv8/36d6a5846f.png)

**Comment by allthefoxes** [comment]
What should it be instead?

**Comment by Dumbaz** [comment]
I am not a 100% sure, as the translation depends on how the convention for the noun Upvote/Downvote is. It could be lots of things

Du musst angemeldet sein um Sachen zu upvoten oder zu downvoten
or
Du musst angemeldet sein um Sachen Upzuvoten oderDownzuvoten
or
Du musst angemeldet sein um Sachen hinauf oder herab zu bewerten

The Problem is that there is no single german word for the term Upvote, and i think Upvote is used as a verb here, which results in [verbifying](http://en.wiktionary.org/wiki/verbify).

**Comment by JordanMilne** [comment]
Thanks for the report! All the translations for reddit.com are crowdsourced and managed through our [CrowdIn project](https://crowdin.com/project/reddit/). If you apply to join the German translation project you should be able to submit a possible correction there.

**Comment by Dumbaz** [comment]
I sent a request for joining the group on crowdin just now.

**Comment by JordanMilne** [comment]
Thanks, just added you to the group. Closing this since it'll be tracked on CrowdIn instead.
