### ISSUE TITLE
Username mentions doesn't work 

### ISSUE THREAD

**Issue by fenec** [reddit/reddit#1283]
I'm running reddit on Ubuntu 12.04 (installed from script)
Created a couple of users and mentioned another user in a comment. 
But it didn't show up in the that user's mentions list. No inboxes at all though the envelope icon on the top right turned orange with number of mentions. 
Tried reddit-flush, reddit-restart, still the same.

**Comment by DorianGray** [comment]
You need to assign a consumer to butler_q. The easiest way to do this is to add this to install-reddit.sh and then re-run the script:

set_consumer_count butler_q 1

You'll notice other calls to set_consumer_count in the file, add it at the end.

**Comment by fenec** [comment]
great. thanks @DorianGray!
