### ISSUE TITLE
Auth providers not in working_set

### ISSUE THREAD

**Issue by grandpaslab** [reddit/reddit#1284]
The new auth providers are not in app_globals.pkg_resources_working_set, so the provider selector is throwing an exception:

Traceback (most recent call last):
  File "/web/reddit/bin/paster", line 9, in <module>
    load_entry_point('PasteScript==1.7.5', 'console_scripts', 'paster')()
  File "/web/reddit/lib/python2.7/site-packages/paste/script/command.py", line 104, in run
    invoke(command, command_name, options, args[1:])
  File "/web/reddit/lib/python2.7/site-packages/paste/script/command.py", line 143, in invoke
    exit_code = runner.run(args)
  File "/web/reddit/lib/python2.7/site-packages/paste/script/command.py", line 238, in run
    result = self.command()
  File "/web/reddit/reddit/r2/r2/commands.py", line 81, in command
    load_environment(conf.global_conf, conf.local_conf)
  File "/web/reddit/reddit/r2/r2/config/environment.py", line 66, in load_environment
    g.setup()
  File "/web/reddit/reddit/r2/r2/lib/app_globals.py", line 440, in setup
    self.authentication_provider,
  File "/web/reddit/reddit/r2/r2/lib/providers/__init__.py", line 45, in select_provider
    raise Exception("unknown %s provider: %r" % (type, name))
Exception: unknown r2.provider.auth provider: 'cookie'

**Comment by spladug** [comment]
Did you run r2's setup.py? 

https://github.com/reddit/reddit/commit/653c6e511339bbb2b39a4737dfe6b5ef827d18be#commitcomment-10292483

**Comment by grandpaslab** [comment]
Yes. I did a fresh clone/install this morning, ran setup, etc.  I actually
noticed this when testing my cron jobs after the install.  I'm not using
upstart or the wrap job script, so maybe it's something to do with my
environment.  E.g. one cron looks like this:

#!/bin/bash

. /etc/default/reddit

export REDDIT_LOG_FACILITY=STDERR

cd $REDDIT_VENV

$REDDIT_VENV/bin/run  \
paster run $REDDIT_ROOT/prod.ini -c 'from r2.lib import subreddit_search;
subreddit_search.load_all_reddits()'

**Comment by spladug** [comment]
I just did a clean test run of the install from the current tip of master and everything seems to check out.  Perhaps there's something going on with the virtualenv? The entry points are installed into the pkg_resources system and should be global.

**Comment by grandpaslab** [comment]
Weird.  'paster points' says it's there.

(reddit)bash-4.1$ paster points r2.provider.auth
[r2.provider.auth]
r2 0.0.0.dev0
cookie = r2.lib.providers.auth.cookie:CookieAuthenticationProvider
    Error loading: 'wrapper_descriptor' object has no attribute
    'im_func'
http = r2.lib.providers.auth.http:HttpAuthenticationProvider
    Error loading: 'wrapper_descriptor' object has no attribute
    'im_func'

If it's working for you though, chances are I've done something funky
without knowing it. I'm about to be done for the day, but I'll let you know
when I figure this out.  Thanks for your help!

J

**Comment by grandpaslab** [comment]
Gah!  Had an old/bogus r2.egg-info in the root of my venv. That and cd-ing
to REDDIT_ROOT in my script has me back in business. Thanks again for your
help.

**Comment by spladug** [comment]
Ah cool, good to know (and TIL about `paster points`!). Glad it's working for you now. Will close this ticket.
