### ISSUE TITLE
Reddit Widget - Insecure Content SSL Errors

### ISSUE THREAD

**Issue by razyr** [reddit/reddit#1291]
When embedding the Reddit widget in an SSL secured site, it causes insecure content errors in the browser.   Although the Reddit URL is being called via https:,  it in turn is loading images via http:.

Specifically it's loading spreddit1.gif and widget_arrows.gif .

![2015-04-06_11-33-57](https://cloud.githubusercontent.com/assets/8116645/7006666/f3edd0b2-dc50-11e4-87f5-55889487684b.png)

**Comment by xiongchiamiov** [comment]
This should be fixed in 406ee35, minus any caching.  Can you verify that for me?

**Comment by razyr** [comment]
I'm not sure about the caching upstream, but on a fresh machine with no cached data spreddit1.gif is loading via https but widget_arrows.gif is still coming in via http.

**Comment by xiongchiamiov** [comment]
Can you give me a link to the page you're looking at?

**Comment by razyr** [comment]
Unfortunately no.  It's in development with no public access.  I have tried three different computers (two Mac, one PC) and Firefox reports the same consistent result/error.  I will give it 24 hours and see if this resolves itself and is in fact just a caching issue at this point.

![2015-04-06_15-01-05](https://cloud.githubusercontent.com/assets/8116645/7010304/0a90ce92-dc6e-11e4-94e0-124953faa775.png)

**Comment by razyr** [comment]
Problem has resolved fully.  Thanks for the quick response.
