### ISSUE TITLE
It's possible to vote on archived posts (and maybe other things) via the API

### ISSUE THREAD

**Issue by ajs124** [reddit/reddit#1292]
So I wanted to fix [this bug](https://github.com/QuantumBadger/RedReader/issues/176) in my favourite reddit client and it turns out, it's not the clients fault.

The code responsible for this, namely the [POST_vote method in api.py](https://github.com/reddit/reddit/blob/03c2100823f5ac72c08f77c5fb95523290464014/r2/r2/controllers/api.py#L1961) and [queue_vote in queries.py](https://github.com/reddit/reddit/blob/063bcf70acfe9a7525370cd39beb24d741e5bf03/r2/r2/lib/db/queries.py#L1666) _seem_ pretty obvious and _should_ not allow voting, since ```store = False``` when this condition: ```thing._age > thing.subreddit_slow.archive_age``` is met, but experimental results contradict this.

Steps to reproduce:
 1. Verify that something is archived by trying to vote on it in the browser and getting an error.
 2. Use the API, e.g. via RedReader to vote on the same post (and maybe also comment, haven't verified that).
 3. Refresh the page in your browser and notice that you have sucessfully cast a vote.

**Comment by QuantumBadger** [comment]
Ideally, attempting to vote on archived posts/comments should result in an HTTP error, so that the API user can know that the vote failed.

**Comment by DogPawHat** [comment]
I've debugged that queue_vote method and the if store statement in queries.py is working correctly, the votes aren't reaching the db, but it does say before the if statement: 
```python
# set the vote in memcached so the UI gets updated immediately
key = prequeued_vote_key(user, thing)
grace_period = int(g.vote_queue_grace_period.total_seconds())
g.cache.set(key, vote_names_by_dir[dir], time=grace_period+1)
```

I don't know a lot about the memcached system, but its not doing the same check on store, so the vote is cached, and it looks like you voted until that cache is cleared. I'm not sure what the best way to fix this would be.

You can duplicate this behavior on a local reddit server by:

1. Set a timestamp on a link, comment or other votable thing to more then 6 months old in PostgresSQL (or have a very old reddit db).
2. Run the following commands:
```shell
sudo /sbin/start --quiet reddit-job-update_reddits
sudo reddit-restart
reddit-flush
```
to flush the cashed and get the UI in sync with the db*.
3. Preform the voting procedure @ajs124 described on the old thing.
4. You'll notice the upvote arrow is orange if you refresh the page, as expected. But if you navigate to /user/{username}/upvoted, you won't see the link in the history.
5. Run step 2 again.
6. Refresh the page and notice that the upvote is gone.

(*I'm pretty sure step 2 is a bit of a clumsy way to get the ui and db in sync. If any dev's can let me know of a more precise way of going about it, that would be nice)

**Comment by DogPawHat** [comment]
As it turns out, posts and comments actually have an archived flag in the JSON, so pretty much every client on the planet can block this from happening on there end. I've fixed [the bug](https://github.com/QuantumBadger/RedReader/issues/176) @ajs124 and @QuantumBadger were talking about in RedReader with [this pr](https://github.com/QuantumBadger/RedReader/pull/223), and I think the devs can close this issue if they are not worried about the votes on archived links/comment showing up in cashe for a few hours.
