### ISSUE TITLE
OAuth compact flow on mobile has beta invitation button

### ISSUE THREAD

**Issue by enoex** [reddit/reddit#1301]
The https://ssl.reddit.com/api/v1/authorize.compact flow for mobile has the "Try Reddit's Beta Website" banner which takes up a very large portion of the screen, especially on smaller phones. The new mobile version of reddit is really slick, but perhaps the oauth flow is not the best place for it. It's causing a lot of confusion for our users when they oauth with reddit.

**Comment by Pokechu22** [comment]
Fixed as of d0d63f3.
