### ISSUE TITLE
[NP Reddit] using www.np.reddit.com has security issues 

### ISSUE THREAD

**Issue by fredghostkyle** [reddit/reddit#1313]
Don't know if this is the correct spot for NP stuff.

When connecting to NP.reddit.com using www.np.reddit.com Google Chrome will think that it is having security issues. Looks like it might just be a SSL/HTTPS error but Google Chrome dose not like it one bit.

**Comment by xiongchiamiov** [comment]
In the future, please report security issues to `security@reddit.com`.

The short answer is that the wildcard cert of `*.reddit.com` covers `www.reddit.com` and `np.reddit.com`, but not the two-level `www.np.reddit.com`, so if you only use a single subdomain at a time things will work as expected.  If you encounter anyone using `www.np.reddit.com`, please tell them that won't work with https.  Thanks!
