### ISSUE TITLE
Underscores show be allowed in CSS class names

### ISSUE THREAD

**Issue by roger-** [reddit/reddit#1317]
According to [this](https://github.com/reddit/reddit/blob/master/r2/r2/lib/validator/validator.py#L1759), a CSS class name with an underscore will fail validation but this appears to be [overly restrictive](https://mathiasbynens.be/notes/css-escapes).

**Comment by xiongchiamiov** [comment]
While it may be legal to have some crazy characters in css classes, that doesn't mean we necessarily want to support them; it makes life a lot easier to keep a restricted set, and I don't think there's any particularly compelling reason for us to do otherwise.

But thanks for the report!
