### ISSUE TITLE
"You've been invited to try out reddit's new beta mobile website!" can appear during oAuth authentication

### ISSUE THREAD

**Issue by QuantumBadger** [reddit/reddit#1318]
The following message:

> You've been invited to try out reddit's new beta mobile website!

Can appear at the top of the compact oAuth authentication page. It then provides a link to go to the reddit mobile site.

I can see this confusing a non-trivial number of users, who may click the link to the mobile homepage, breaking the authentication flow.

![reddit_auth_fail](https://cloud.githubusercontent.com/assets/2998158/7669625/eb431626-fc75-11e4-80cf-8460cdf69ef4.png)

Clicking the link actually sends the user to a 404 page: https://m.reddit.com/404.

**Comment by enoex** [comment]
Bumping this for visibility, I also have the same [issue](https://github.com/reddit/reddit/issues/1301)

**Comment by HeroCC** [comment]
This appears when signing into reddit from the Bacon Reader app as well, as it uses Oauth

**Comment by 13steinj** [comment]
Also occurs on Sync for Reddit

**Comment by Pokechu22** [comment]
Fixed as of d0d63f3.

**Comment by umbrae** [comment]
Thanks for cleaning up for us @Pokechu22!

**Comment by 13steinj** [comment]
@umbrae  it was @Deimos  that made the change.

**Comment by umbrae** [comment]
I'm aware, I'm just grateful for someone remembering to come and comment on
the issues.
