### ISSUE TITLE
Missing operand - install script for Ubuntu

### ISSUE THREAD

**Issue by yakutsa** [reddit/reddit#1319]
I have tried to install github reddit using install script for Ubuntu. I am using Ubuntu 12.04 on VPS but I get the following error:

+ '[' '!' -d /home//src ']'
+ mkdir -p /home//src
+ chown /home//src
chown: missing operand after `/home//src'
Try `chown --help' for more information.

Why am I getting this error?

**Comment by spladug** [comment]
It looks like `$REDDIT_USER` is not defined for some reason. It should come automatically from the `sudo` environment if you're running the script that way -- otherwise, you'll need to set it before running the script.

e.g.

```
$ sudo ./install-reddit.sh
```

or

```
# export REDDIT_USER=myusername
# ./install-reddit.sh
```

**Comment by yakutsa** [comment]
@spladug , 

Yes, you are right.

Thank you for your great support.
