### ISSUE TITLE
You can't delete (private) messages (PMs)

### ISSUE THREAD

**Issue by n1trux** [reddit/reddit#1320]
I just found out you can't delete private messages, also called PMs, after you read them. This is a tad inconvenient, especially since it seems that they are stored for all eternity.

Please fix this.

I'm sorry if this is a duplicate, but I did a quick search in issues and PRs and didn't find anything.

EDIT: I am so sorry, just found out that the Issues here are only for confirmed bugs. Opened a post in /r/ideasfortheadmins instead: https://www.reddit.com/r/ideasfortheadmins/comments/36jdrj/make_it_possible_to_delete_messages/

**Comment by allthefoxes** [comment]
Can you please close this issue? Thanks @n1trux 

cc @umbrae
