### ISSUE TITLE
 "Operation not allowed" for gfycat gifs

### ISSUE THREAD

**Issue by franciscocorrales** [reddit/reddit#1325]
I am getting an error message "**Operation not allowed**" when trying to see a gif from gfycat, in Reddit´s Android app.   

I'm I the only one?   Is that a bug ? I don't find anything on Internet about this..

Screenshot:
http://i.imgur.com/Obugt1i.jpg

The app is: **reddit is fun**
https://play.google.com/store/apps/details?id=com.andrewshu.android.reddit&hl=en

**Comment by xiongchiamiov** [comment]
Which Android app?

**Comment by franciscocorrales** [comment]
@xiongchiamiov  sorry, forgot to mention, I edited my post. 

Thanks.

**Comment by xiongchiamiov** [comment]
Yes, but don't worry about it. :)

Try the folks over at [/r/redditisfun](https://www.reddit.com/r/redditisfun).

**Comment by franciscocorrales** [comment]
ok.

I make a post in reddit ...

Link if anybody get's here...
http://www.reddit.com/r/androidapps/comments/37qsfk/error_operation_not_allowed_for_gfycat_gifs_in/
