### ISSUE TITLE
Request: API adjustment: Allow retrieving of user karma when requesting posts/comments

### ISSUE THREAD

**Issue by BrentNewland** [reddit/reddit#1326]
Reddit is becoming popular enough that I've noticed a significant number of accounts with 1,000,000 karma. Which is concerning to me - that tells me there's a large company or a giant farm behind many of these accounts, maybe even voting brigades, manipulating the content I see.

I'd like to be able to see this stuff with RES, but that would require a separate API call for every individual user. If Reddit's API had an option to return link and comment karma values for each user when requesting posts and comments, RES would be able to do this.

It would also allow RES to add another long requested feature, the ability to highlight or hide users who have negative karma (because they are most likely trolls).

**Comment by allthefoxes** [comment]
The API already does allow this. The issue is api limits. You can only make a call every 2 seconds. There is no real reason for this to be changed for one specific instance.

**Comment by BrentNewland** [comment]
You can limit conversation to a single thread.

Please reread what I posted.

I'm not asking Reddit to allow lots of API calls. Obviously.

I'm asking for Reddit to make an addition to its API so more data can be returned in a single API call, eliminating the need to make multiple API calls.

Also, /r/ideasfortheadmins doesn't work. Ever.

@allthefoxes No reason to close?

**Comment by allthefoxes** [comment]
/r/ideasfortheadmins works fine. Admins have implemented suggestions from there, its just that most suggestions are bad.

And you are right, I did misread, and I apologize.

Either way, feature requests belong on /r/ideasfortheadmins. Github is for PRs and confirmed bug reports.

**Comment by umbrae** [comment]
Thanks for your request Brent - @allthefoxes is correct though that /r/ideasfortheadmins is the right place for feature requests, [as mentioned in CONRIBUTING.md](https://github.com/reddit/reddit/blob/master/CONTRIBUTING.md).

Feel free to submit it over there for discussion. We do read them.
