### ISSUE TITLE
posts in subs with low activity keep rank too long in multireddits

### ISSUE THREAD

**Issue by dpk** [reddit/reddit#1334]
Multireddits do a good job of letting content from subreddits with low activity levels blend into the mix even when they're competing with many busy subs. Unfortunately posts from those subreddits tend to keep their high ranks and stay on the front page even as everything else changes around them. Right now one of my multis has a post from a very quiet sub that's been there for 3 months; the second-oldest post is only 3 days old (which is still too old in my opinion, since it also comes from one of the quieter subs in the multi).

I'm not familiar with the reddit codebase, and I just spent 15 minutes or so hunting for the formula used to rank posts in multireddit and couldn't find it, but I'm guessing it applies a positive factor based on the post's score and the busyness of the subreddit it comes from (which could take various forms: number of subscribers, average score of postings in that sub, etc.) and a negative factor based on the amount of time since it was posted and again the busyness of the subreddit it's in.

I propose that the negative busyness factor of *all* posts in a multireddit should be the same — perhaps the median busyness of all the subs in that multireddit. That way, posts from smaller subreddits will (hopefully) still rise just as quickly, but also fall off the front page at an appropriate speed.

(Forgive me if my understanding of the ranking formula is completely wrong-headed. The problem stands even if my proposed fix is impractical.)

**Comment by xiongchiamiov** [comment]
I believe multireddits are constructed in the same way as the front page; a description of that process is [here](https://www.reddit.com/r/dataisbeautiful/comments/2lhhiu/the_reddit_frontpage_is_not_a_meritocracy/clv5d5j?context=3).

This probably isn't the best forum for discussing this type of change, though, given that it's not so much a bug as an idea on how we might improve listings.  I'm going to close this, but please feel free to start a discussion in [/r/ideasfortheadmins](https://www.reddit.com/r/ideasfortheadmins).
