### ISSUE TITLE
Inconsistencies between /by_id/ and /api/info/

### ISSUE THREAD

**Issue by rtheunissen** [reddit/reddit#1347]
[GET /by_id/*names*](https://github.com/reddit/reddit/blob/master/r2/r2/controllers/listingcontroller.py#L668) has an internal flag called `ignore_missing` set to `True`, but [GET /api/info/](https://github.com/reddit/reddit/blob/master/r2/r2/controllers/api.py#L182) inherits the default value as `False`. Is there a specific reason why:

- /by_id/ can't be made open to both Comment and Link
- /api/info/ doesn't want `ignore_missing` to be `True`?

If the limit is 100 I can't see how this would be a problem.

Some examples that show what the issue is:

[/by_id/ which ignores bad names](https://www.reddit.com/by_id/t3_39zje0,t3_39zje1,t3_invalid.json)
[/api/info/ which yields nothing instead](https://www.reddit.com/api/info/.json?id=t3_39zje0,t3_39zje1,t3_invalid)

**Comment by rtheunissen** [comment]
:eyeglasses: please I can give :moneybag: as I'm currently blocked by this. :<

**Comment by xiongchiamiov** [comment]
I think this is closed by 5a0b537cd541d8546e19bcfc5b73fa89c996ad5d; if not, feel free to reopen (or ping us to do so).
