### ISSUE TITLE
No fallback when JavaScript is disabled.

### ISSUE THREAD

**Issue by Y-Less** [reddit/reddit#1350]
It is impossible to post a comment, or even view some comments, with JavaScript disabled via the likes of NoScript.  This seems like a massive oversight given that they should only require basic <form> tags that are a basic part of HTML.

**Comment by jedberg** [comment]
It was totally intentional and not an oversight.  The user experience without Javascript is terrible because it requires a page reload, and also the development effort to make a fallback experience for the very few people who actually have Javascript off just isn't worth it.

**Comment by Y-Less** [comment]
Surely a page reload is a better experience than being totally unable to comment?

**Comment by Y-Less** [comment]
On a related note, I tried sending a PM today.  i wrote it, clicked "send", and had a new page load with an error message.  So not only did I get the page load you were trying to avoid, but got it without the pleasure of having my message be sent, and clicking "back" presented a freshly blank textbox with my message gone.

**Comment by kkirsche** [comment]
@jedberg a page reload is worse than not using the product? That's pretty bad UI IMHO

**Comment by 13steinj** [comment]
@kkirsche @jedberg A page reload isn't bad, if only used on the fallback system. However I do agree that at this time implementing such a system for the few users that disable JS is not worth it.

**Comment by Y-Less** [comment]
More justification for disabling JavaScript.  With more news like this constantly surfacing, I wouldn't be surprised if the number of users without JavaScript increases rather than decreases:

https://webtransparency.cs.princeton.edu/webcensus/index.html

**Comment by ajacksified** [comment]
fwiw, we're currently rebuilding mobile web in such a way that most, if not all, of the functionality works with javascript disabled; we expect that work to be live in a couple months, maybe sooner. That technology will almost certainly make its way back to desktop, although it'll be some time before it's implemented. Closing this for now.

**Comment by Y-Less** [comment]
Can we re-open this now?  I've seen that there is a new mobile web site out, which I assume was the one you were talking about, so any idea on when the correct development methods will make it to the main website?  Thanks.
