### ISSUE TITLE
"related" tab can't detect redirect urls?

### ISSUE THREAD

**Issue by TapirLiu** [reddit/reddit#1362]
Following urls will go to the same page finally:
https://stackoverflow.com/questions/11227809/why-is-processing-a-sorted-array-faster-than-an-unsorted-array
http://stackoverflow.com/q/11227809/215042
http://stackoverflow.com/a/11227902/215042

But the "Related" algorithm can't detect them.

**Comment by bsimpson63** [comment]
Knowing about other sites' url structure or following urls to the "true" destination is not something we want to do.
