### ISSUE TITLE
Running install-reddit.sh "The crashed program seems to use third-party or local libraries"

### ISSUE THREAD

**Issue by theonlylawislove** [reddit/reddit#1366]
This happens as of "28170a8c9c5d2eed8e40550a646859205c3bc047".

```
> lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 12.04.5 LTS
Release:	12.04
Codename:	precise
```

This is a fresh 32bit VM. I tried with VMWare/HyperV/VirtualBox. All same thing.

![image](https://cloud.githubusercontent.com/assets/523150/8661528/305147f0-2986-11e5-857d-6c2788ada703.png)

**Comment by spladug** [comment]
Those are part of the reddit code.  Do you happen to have an actual traceback for the crash? reddit's not usually run in a graphical environment, and definitely not in 32 bit, so it may be a good idea to try 12.04 x64.

**Comment by TheEnigmaBlade** [comment]
I've had the same issue, but I believe its benign as the site instance is completely unaffected.

It can be "fixed" by booting the VM into the command line, but otherwise the messages can be ignored.
