### ISSUE TITLE
'Reasons to create a reddit' broken

### ISSUE THREAD

**Issue by HeroCC** [reddit/reddit#1372]
![Bug](http://i.gyazo.com/19221d64694e8b88c745e0abd654d7eb.png)
This happens with or without without any plugins / RES. I made an incognito window and it tested the same. This is on reddit.com

**Comment by xiongchiamiov** [comment]
Thanks!  [Should be fixed now](https://www.reddit.com/r/bugs/comments/3exsqb/reason_to_create_reddit_18_and_reason_to_create/ctjh96w).
