### ISSUE TITLE
Valid Password is rejected

### ISSUE THREAD

**Issue by facetoe** [reddit/reddit#1374]
If I logout, then create a new account, then logout again I am unable to login to any account. 

To be clear, I am logged in as `medicalizawhat` (real reddit name) and I logout. I then create an account `wtfthrowawayfuck` with the password  `password`. From this point on I can no longer login as either `medicalizawhat` or `wtfthrowawayfuck`. In each case I am told that the password is incorrect (it isn't). In addition the i3pystatus reddit plugin (https://github.com/enkore/i3pystatus/blob/master/i3pystatus/reddit.py) also reports that my password is wrong, yet I have not changed it. 

I'm running:
`Linux facetoe 4.1.3-1-ARCH #1 SMP PREEMPT Wed Jul 22 20:37:12 CEST 2015 x86_64 GNU/Linux`

with Firefox version:

`Firefox 39.0`

If you need any more information let me know.

**Comment by rram** [comment]
This tracker is for confirmed bugs in the code only. Please send mail to contact@reddit.com. Also please do not create bug reports with credentials in them.

**Comment by facetoe** [comment]
I will submit a report to  contact@reddit.com but this was the obvious place to file our bug. The credentials I provided were throwaway accounts that trigger the bug, to aid in your testing. 

I think it's funny that your bug tracker here is for confirmed bugs only. Without investigation, how can you confirm them?

**Comment by mechler** [comment]
I'm having this problem as well. I have emailed a description of the problem to contact@reddit.com.
