### ISSUE TITLE
Search fails on local reddit-vagrant setup

### ISSUE THREAD

**Issue by codehate** [reddit/reddit#1382]
This is what I get when I search something:
```
search failed

Our search machines are under too much load to handle your request right now. :( Sorry for the inconvenience. Try again in a little bit -- but please don't mash reload; that only makes the problem worse.
```

**Comment by xiongchiamiov** [comment]
By default, search uses Amazon Cloudsearch, which obviously isn't available on your local vm (as it's an external service).

A wonderful outside contributor recently added a Solr option for search (see #1289); you can use that instead by changing [`search_provider`](https://github.com/reddit/reddit/blob/master/r2/example.ini#L437) to "solr".  There's more info on that [here](https://github.com/reddit/reddit/tree/master/solr).
