### ISSUE TITLE
babel is too slow on local instance

### ISSUE THREAD

**Issue by joybro** [reddit/reddit#1389]
My local instance of reddit takes more than 20 seconds to load frontpage if I changed my preference language to any language but English('en'). I found out that babel consumes most of the loading time.

Here is cprofile result;
```
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
314194    6.045    0.000   12.745    0.000 /usr/lib/python2.7/dist-packages/babel/messages/jslexer.py:130(tokenize)
2110188    3.047    0.000    3.047    0.000 {method 'match' of '_sre.SRE_Pattern' objects}
21564    1.433    0.000    1.457    0.000 /usr/lib/python2.7/dist-packages/babel/util.py:174(__setitem__)
9    1.001    0.111    7.583    0.843 /usr/lib/python2.7/dist-packages/babel/messages/pofile.py:75(read_po)
123    0.858    0.007   13.653    0.111 /usr/lib/python2.7/dist-packages/babel/messages/extract.py:449(extract_javascript)
314189    0.682    0.000    1.053    0.000 /usr/lib/python2.7/dist-packages/babel/messages/jslexer.py:57(__new__)
314189    0.662    0.000    0.662    0.000 /usr/lib/python2.7/dist-packages/babel/messages/jslexer.py:65(indicates_division)
465584    0.655    0.000    0.655    0.000 {method 'findall' of '_sre.SRE_Pattern' objects}
```

**Comment by spladug** [comment]
Are you doing development or running an install? If it's the latter, turning off `debug` in the config and ensuring you've run `make` to build updated statics should make this go away -- the slowest bits of babel happening on load are generating the translations for the javascript.  We special-cased "en" in that case as a development shortcut because that's what the string message ids are written in.

**Comment by joybro** [comment]
@spladug, thanks for comment.

Yes, I'm running an install. But turning off `debug` doesn't resolve this slowdown. Here is what I've done to turn off `debug`
1. Add `debug = false` to development.update
2. Run `make`
3. Got following output
```
reddit@localhost:~/src/reddit/r2$ make
[+] including definitions from Makefile.py
[+] adding make rules from plugin "meatspace"
[+] adding make rules from plugin "about"
[+] adding make rules from plugin "liveupdate"
python setup.py build_ext --inplace
running build_ext
copying build/lib.linux-x86_64-2.7/r2/lib/sgm.so -> r2/lib
copying build/lib.linux-x86_64-2.7/r2/lib/wrapped.so -> r2/lib
copying build/lib.linux-x86_64-2.7/r2/lib/db/_sorts.so -> r2/lib/db
copying build/lib.linux-x86_64-2.7/r2/lib/utils/comment_tree_utils.so -> r2/lib/utils
copying build/lib.linux-x86_64-2.7/r2/lib/utils/_utils.so -> r2/lib/utils
copying build/lib.linux-x86_64-2.7/r2/lib/mr_tools/_mr_tools.so -> r2/lib/mr_tools
copying build/lib.linux-x86_64-2.7/Cfilters.so -> 
./updateini.py example.ini development.update > development.ini || rm development.ini
```

Should the translated javascript be cached on non-debug mode? On my environment, bebel translates javascript everytime I reload a page.

**Comment by spladug** [comment]
Apologies, I should've said to set `uncompressedJS` to `false`.

**Comment by joybro** [comment]
Thank you @spladug! It works like a charm! :D
