### ISSUE TITLE
Cannot reply to messages from OAuth2 clients with '*' scope.

### ISSUE THREAD

**Issue by turnage** [reddit/reddit#1391]
OAuth2 clients that authenticate via password get tokens with '*' scope, implying they have all scopes. (?)

However, POST_comment, when it checks that an OAuth2 client with '*' has the correct scopes, does not approve it. I believe this is check is [here](https://github.com/reddit/reddit/blob/9ccda2c49fe17321dad97e20bb6b2799e2e006d1/r2/r2/models/token.py#L310), called from POST_comment [here](https://github.com/reddit/reddit/blob/2fe99ad867446e77afb6acdbd851a1366541c764/r2/r2/controllers/api.py#L1829).

In the mean time, OAuth2 clients who cannot use POST_comment on t4_ types can explicitly request "submit" and "privatemessages" scopes, and then the request will work.

POST_comment for OAuth2 clients with '*' is working as expected for t1_ and t3_ types.

**Comment by kjoconnor** [comment]
Thanks for the detailed report! I'm checking this out right now.

**Comment by kjoconnor** [comment]
We've got a fix in place and we'll roll it out Monday. Thanks again for the report!

**Comment by kjoconnor** [comment]
Fixed [here](https://github.com/reddit/reddit/commit/7d32950cbc0132a375cfcf54d277ab871b752c27), thanks again!
