### ISSUE TITLE
Infinite reloading of static resources

### ISSUE THREAD

**Issue by Axure** [reddit/reddit#1392]
Description:
https://www.reddit.com/r/redditdev/comments/3htcjb/a_new_installation_very_slow_loading_a_enormous/

>Viewing from the timeline, it loads countless js files like embed.js?v=1440098988.94 and countless less files like utils.less. And I believe most of them are duplicate. It also says a lot of messages like the following in the js console.
>less: parsed http://regit.dog/static/css/reddit.less?v=1440098988.93 successfully. less-1.4.2.js?v=1440098988.95:5731 less: css for http://regit.dog/static/css/reddit.less?v=1440098988.93 generated in 29224ms less-1.4.2.js?v=1440098988.95:5731 less: css generated in 29226ms
>Even worse, it reloads everything every 1 or 2 minutes.

After I have set uncompressedJS to false, but now:

>But the infinite reloading problem persists. And two pngs are missing. I guess that may be the cause for reloading.
>GET http://regit.dog/sidebar-grippy-hide.png 404 (Not Found) reddit-init.en.6EyW22KQmuc.js:1 GET http://regit.dog/snoo-upside-down.png 404 (Not Found)curCSS

**Comment by xiongchiamiov** [comment]
This issue tracker is for confirmed bugs in the code, please; if you're not getting the answers you're looking for in /r/redditdev, you can always drop by `#reddit-dev` on freenode and see if anyone there can help.

Thanks.
