### ISSUE TITLE
Some translation strings are broken

### ISSUE THREAD

**Issue by joybro** [reddit/reddit#1412]
2fe99ad867446e77afb6acdbd851a1366541c764 changed some strings in reddit, not ones in reddit-i18n. So those strings are not being translated now.

What is the proper way to fix this? Do we need to change strings in reddit-i18n following 2fe99ad867446e77afb6acdbd851a1366541c764, or revert it?

**Comment by joybro** [comment]
@florenceyeun please check this

**Comment by Pokechu22** [comment]
I believe that they are changing a bunch of strings because they are updating their style guide, and i18n changes will follow sometime.

**Comment by xiongchiamiov** [comment]
Periodically we run a script that pulls translated strings out of the codebase and syncs them up with the CrowdIn, and that eventually makes its way into reddit/reddit-i18n.
