### ISSUE TITLE
Invalid JSON when requesting from "oauth.reddit.com"

### ISSUE THREAD

**Issue by Sharpiro** [reddit/reddit#1417]
test strings: 
```
https://oauth.reddit.com/r/destinythegame/comments/3mqjza.json
https://oauth.reddit.com/r/destinythegame/comments/3mqjza
```

The above string only returns data when authenticated.  But the data that it receives looks like JSON, but it is unable to be parsed by Newtonsoft/Chrome/JS.  If I just use the base reddit domain with no auth, the JSON is parsable.

Is this intended?

**Comment by 13steinj** [comment]
If you have a is this intended question, it's better to ask /r/redditdev and crosspost to /r/bugs. The github is supposed to be for confirmed issues.

That said, if you do make a post, I'd ask "what exactly do you mean by cannot be parsed?"

**Comment by 13steinj** [comment]
Also, considering praw can parse the json and all it uses is the json.loads() method, and that works, maybe you have to request things differently / parse a specific part of the request.

**Comment by Sharpiro** [comment]
Nevermind.  I was misusing the Newtonsoft JSON API.  Thanks.
