### ISSUE TITLE
Use reddit for in-app feedback

### ISSUE THREAD

**Issue by durandt** [reddit/reddit#1426]
Hi, 

Would it be allowed to use reddit's API to provide an in-app feedback feature? 

The app would have a menu that would bring the user to a specific thread where he would see others comments. The user would be able to log in to Reddit via OAuth to vote or comment on the thread. 

Regards,

**Comment by 13steinj** [comment]
I don't understand why that would be a problem, but you may want to ask /r/help / /r/redditdev. This Github issues panel is meant for confirmed, active issues.

**Comment by durandt** [comment]
Ok thank you. I'm not very used to reddit (I don't even have an account yet :-x ) so thank you for the tips!

I'll close the issue then.
