### ISSUE TITLE
When replying to private messages, I am unable to select multiple paragraphs for quoting

### ISSUE THREAD

**Issue by nguyenmp** [reddit/reddit#1430]
There is a feature where you can highlight some text in a message and press "reply".  The reply will be prepopulated with a quote of the selected text.  However, if that selected text spans more than a single paragraph, then it only quotes the first paragraph.  I would like to be able to quote multiple paragraphs.

**Comment by 13steinj** [comment]
This github issue panel is for *confirmed*, active issues. Please make a /r/bugs post instead.

**Comment by nguyenmp** [comment]
Closing as per comment by @13steinj 

I've made a post to /r/bugs [here](https://www.reddit.com/r/bugs/comments/3o958r/when_replying_to_private_messages_i_am_unable_to/).
