### ISSUE TITLE
Reddit buttons are broken 

### ISSUE THREAD

**Issue by jonathan-s** [reddit/reddit#1432]
The reddit buttons are broken, when you try to add the script of to a page you created you get the error `SyntaxError: unterminated string literal`.
 
It has also been confirmed here:
https://www.reddit.com/r/bugs/comments/3o1839/most_of_the_buttons_are_broken_error_unterminated/

**Comment by alisharif2** [comment]
Has this bug been fixed?

**Comment by kjoconnor** [comment]
Whoops yep, this was fixed last month:

3308b8186f7c68118de621647e3b890934ce2294
