### ISSUE TITLE
RSS link incorrectly built for Elixir

### ISSUE THREAD

**Issue by jc00ke** [reddit/reddit#1434]
https://www.reddit.com/r/elixir renders the RSS link as
`https://www.reddit.com/r/elixir/.rss` but should be
`https://www.reddit.com/r/elixir.rss`

**Comment by 13steinj** [comment]
I don't beleive it actually matters; same with the json a compact render styles, so, this may be better suited for /r/bugs.

**Comment by jc00ke** [comment]
Looks like you are right, though I thought the first time around it didn't render correctly. I'll close for now and see if I can repro at some point.
