### ISSUE TITLE
/api/morechildren.json returns a flattened comment hierarchy

### ISSUE THREAD

**Issue by aleclarson** [reddit/reddit#1436]
```
https://www.reddit.com/api/morechildren.json?api_type=json&link_id=t3_3oee51&children=cvwn5l4&limit=1
```

I was expecting the URL above to return only one comment. I tried with and without `limit=1` and got the same results.

[Here's a pastebin of the JSON response.](http://pastebin.com/GeFar5Dz)

The structure resembles a flattened comment hierarchy.

```
"things": [
  { the comment specified by "children=cvwn5l4" },
  { a reply to cvwn5l4 }
  { a "more" token for the reply }
  ...
  { a "more" token for the first comment }
]
```

1. Shouldn't any replies be nested in the appropriate `replies` object?

2. Why isn't `limit=1` respected?

**Comment by darkryder** [comment]
Is this bug accepted? OK to start working on a patch?

**Comment by aleclarson** [comment]
`depth=1` is also not respected, despite `https://www.reddit.com/r/videos/comments/3oee51.json?depth=1&limit=10` working as expected. It would be great if these were consistent with each other, seeing as they are used for the same purpose.

**Comment by 13steinj** [comment]
The depth parameter isn't really meant to be used on anything other than article listings. By "on anything other", that includes MoreComments (MoreChildren); so I assume that in and of itself isn't a bug.

I don't believe the flatlist is an actual bug either...however I am definitely seeing weird behavior on a local install related to it; that is, any modmail when the threaded modmail feature is enabled has the same issue both api wise *and* visually, the same goes with *some*, but not all comments. Could be possible that what renders it in a proper chain is closed source? But I doubt it. Or a feature flag isn't enabled somewhere.

That all said and done I recommend posting to /r/redditdev. The "bug" in and of itself isn't actually confirmed, and this issue panel is for confirmed issues. I'm sure someone on there will answer the question there quicker as well.

**Comment by aleclarson** [comment]
> The depth parameter isn't really meant to be used on anything other than article listings. By "on anything other", that includes MoreComments (MoreChildren); so I assume that in and of itself isn't a bug.

But how is that justified? Both `[/r/subreddit]/comments/article` and `/api/morechildren` are for loading comments. Why can't they both support `depth=X` and `limit=X`?

&nbsp;

> I don't believe the flatlist is an actual bug either

What's the point of returning a flatlist for `/api/morechildren`, rather than nested `replies` objects like `[/r/subreddit]/comments/article` does it?

**Comment by 13steinj** [comment]
> But how is that justified? Both [/r/subreddit]/comments/article and /api/morechildren are for loading comments. Why can't they both support depth=X and limit=X?

You never ask a "can" question in the world of programming unless it's painstakingly obvious that th r answer is no. It can. Practically always. But the question should be, "Should it?"

There are other endpoints also for loading listings of things, including comments, that don't support it. Limit, I mean. And there is no way to actually use such a limit browser side, so, there would be an inconsistency there.

When it comes to depth, well, you said it yourself. It supposedly returns a flat list. Even assuming that that is a bug, we go back to the problem of a browser side inconsistency.

**Comment by bsimpson63** [comment]
The `/api/morechildren` endpoint is specifically for the "load more comments" buttons on the html view of reddit.com. It's definitely a bit funky, but what you're asking for is something completely different, so this is not a reddit bug.
