### ISSUE TITLE
Unable to build on Ubuntu 12.04.5 (initctl: Event failed)

### ISSUE THREAD

**Issue by vortexxx192** [reddit/reddit#1437]
Hi all,

I would like to start learning reddit's code and maybe contribute some, but failed to run it in my Virtualbox'ed Ubuntu (the host machine is running OS X 10.10.5). Tried both x32 and x64 versions of Ubuntu, but receiving the same error when trying to execute sudo reddit-start  -- initctl: Event failed

I tried the following:
1. Installed fresh new Ubuntu in Virtualbox
2. sudo apt-get install update
3. sudo apt-get install git
4. git clone https://github.com/reddit/reddit.git
5. cd reddit
6. sudo ./install-reddit.sh > install_log

Here is my install_log: http://pastebin.com/1UPQyiKx

Also having errors right after install like in #1366

Thank you for your help

**Comment by 13steinj** [comment]
You may just want to try the process mentioned in the install guide near the top about the install script, just wget the script and run, it does the rest.

Also this github issue panel is for confirmed issues, you are looking for /r/redditdev

**Comment by Pokechu22** [comment]
That error after running `sudo reddit-start` means that **reddit has already started**.  You should be able to connect to it now.  (Or you need to set up `/etc/hosts` on the host machine)

I do wish the error was clearer, but I don't know how easy that is to fix.

**Comment by kjoconnor** [comment]
This tracker is for confirmed bugs only, please post to [r/redditdev](https://www.reddit.com/r/redditdev) instead. Thanks!
