### ISSUE TITLE
Reddit bot fails on cloudflare's flexible ssl

### ISSUE THREAD

**Issue by luukholleman** [reddit/reddit#1438]
It seems that the reddit bot doesn't accept cloudflare's flexible ssl. When I'm submitting a link with an https url the 'suggest title' button fails, while the same url with http works. 

Steps to reproduce:

* Submit link on /r/test
* Fill link with http://parkitectnexus.com/files/ee04ce7cdf/alfresco-pond
* Press suggest title, it works
* Now fill it with the https version https://parkitectnexus.com/files/ee04ce7cdf/alfresco-pond
* Press suggest tile, doesn't work anymore

The nginx access log also doesn't mention any request from the reddit bot when it's using https, when using http, I can see a visit. To make sure nginx is logging both http and https requests I checked it with my browser and fb's og debugger. Both requests are logged correctly.

This is probably related to determining the thumbnail, reddit never shows a thumbnail of my website even though I specified an og:image. But that og:image url also uses flexible ssl.
Edit: confirmed that it also fails on thumbnails. Posting my staging website (that fully runs on http) to reddit will load a thumbnail.

**Comment by kjoconnor** [comment]
This is due to [SNI](https://en.wikipedia.org/wiki/Server_Name_Indication), which the current version of our scraper doesn't support. We should be reworking that fairly soon to add that. Thanks for the report!

**Comment by ikkentim** [comment]
Any update on this? Still having this problem

@kjoconnor

**Comment by johanson** [comment]
Yes, the problem still exists.

Probably because of old Python that lacks SNI support?

**Comment by kjoconnor** [comment]
Yep, we still don't unfortunately. The rework got put on hold but is still eventually planned. I don't have an ETA for this being fixed. Sorry!

**Comment by reaperhulk** [comment]
Depending on how this is implemented fixing it is potentially as simple as replacing the `requests` dependency with `requests[security]`. This will add pyOpenSSL and (provided the underlying host is not CentOS 5, which predates OpenSSL 0.9.8f). Alternately upgrading to Python 2.7.9 or better will also provide SNI support natively (and requests will use it automatically).

**Comment by JMacLulich** [comment]
Just adding my 2cents, this is a real problem because it forces CDN users (at least on Cloudfront) to have to use a dedicated IP at $600/month just to support the reddit bot! Facebook and co already support SNI....how hard is it to support this?

**Comment by johanson** [comment]
@JMacLulich + half of the Internet is behind Cloudflare and many are using their (free) flexible https plan, meaning SNI.

**Comment by JMacLulich** [comment]
@johanson exactly, we just had to move to CloudFlare and pay $200/month for their Paid SSL and have them issue the cert all because of the reddit bot. Seriously guys, this is beyond a joke.

**Comment by kjoconnor** [comment]
We're well aware it's an issue, but as it only affects title suggestions and media previews, not actual post submissions, etc., it's not the highest priority for us. I'll be locking this for now as there's not much more to add.

Thanks.

**Comment by spladug** [comment]
FYI this has now been taken care of.

**Comment by jnachtigall** [comment]
@spladug Meaning it has been fixed and released? (does not seem so). Since this bug is closed, any way to get a notification when the fix has been rolled out?

**Comment by spladug** [comment]
Yes, it's rolled out. Do you have an example of an SNI'd domain that is not working? I've tested with several and it does appear to work.

**Comment by jnachtigall** [comment]
@spladug You're right, works now. 👍

**Comment by johanson** [comment]
@jnachtigall If you have submitted something that is using SNI, just hit 'retry thumb'. It works now. Most likely, the old posts won't retroactively have the thumbs re-fetched.
