### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by awesomekid** [reddit/reddit#1468]
Just a little thing that i think you could update the design on the main page could look a little bit greater maybe matrial design or just make it look more modern. Thanks for your time.

**Comment by 13steinj** [comment]
Now; I'm a hypocrite of this; but, from contributing.md:

> Before you submit an issue or pull request, please keep in mind a couple of considerations:
> 
> Don't use GitHub issues for feature requests. If you have a feature request, please submit it to /r/ideasfortheadmins instead. Please note that while we do subscribe to /r/ideasfortheadmins, the presence of a response or lack thereof has no indication as to whether the idea will actually get implemented.

**Comment by awesomekid** [comment]
Sorry

**Comment by 13steinj** [comment]
No need for sorry :P. Like I said I'm a hypocrite of it; and I don't represent reddit.
