### ISSUE TITLE
French translation on search error page

### ISSUE THREAD

**Issue by hyptos** [reddit/reddit#1470]
Hi,

When I tried to search for something on reddit in "fr" language, I got an error that the search couldn't be done and I should wait and not refresh the page.

There is a grammar mistake in it : "La recherche a échouée" instead of "La recherche a échoué"

It's just a wording problem.

That's all.

**Comment by Pokechu22** [comment]
FYI, reddit's translations are crowsdsourced.  Check out [/r/I18n](//reddit.com/r/i18n) for more info.

**Comment by kjoconnor** [comment]
As @Pokechu22 says, please check out that subreddit for more info on how to get these translation errors fixed. Thanks!
