### ISSUE TITLE
Reddit install script does not escape $ on the nginx ssl config

### ISSUE THREAD

**Issue by RoundSparrow** [reddit/reddit#1480]
https://github.com/reddit/reddit/blob/master/install-reddit.sh#L470

Line 470 of the script, the map line - fails to work because the $ are not written to the file but instead resolved.

Lines 496 and 497 have the same error?

**Comment by jkingsman** [comment]
Looks like this was fixed in 8693efe.

**Comment by spladug** [comment]
Yup, thanks!
