### ISSUE TITLE
Missing box url in Vagrantfile

### ISSUE THREAD

**Issue by kochis** [reddit/reddit#1487]
The box listed in the Vagrantfile is no longer available (404)

https://github.com/reddit/reddit/blob/master/Vagrantfile#L61

Url: https://cloud-images.ubuntu.com/vagrant/trusty/20151201/trusty-server-cloudimg-amd64-vagrant-disk1.box

**Comment by umbrae** [comment]
Yeah, this is known and we're thinking about how to fix it. For now you can
replace the date string in the url with "current" to get the latest version
and update the sha256sum to match.

**Comment by khanly** [comment]
change to:
  
config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/20151218/trusty-server-cloudimg-amd64-vagrant-disk1.box"
  config.vm.box_download_checksum = "0975e1a73226563ec7791c9b2fd114a57e918e401f82f4778a44e43040e39609"
  config.vm.box_download_checksum_type = "sha256"

**Comment by sevazhidkov** [comment]
@khanly Same:
```
iMac-Mac:reddit mac$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'trusty-cloud-image' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Adding box 'trusty-cloud-image' (v0) for provider: virtualbox
    default: Downloading: https://cloud-images.ubuntu.com/vagrant/trusty/20151218/trusty-server-cloudimg-amd64-vagrant-disk1.box
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

The requested URL returned error: 404 Not Found
```

**Comment by kjoconnor** [comment]
We've decided to just always stick with current absent a better solution for now.

https://github.com/reddit/reddit/commit/b1550aed10fd3ac7695c1ecb7ed15e308cdcb7ba
