### ISSUE TITLE
Reddit API HTTP error 429 when 'User-agent' not defined in header

### ISSUE THREAD

**Issue by GalMoore** [reddit/reddit#1493]
When running the below encountered an HTTP Error 429 that implies ‘Too Many Requests’:

```
import requests
import json

r = requests.get('https://www.reddit.com/r/worldnews.json')

theJSON = json.loads(r.text)
print theJSON
```
By adding a 'User-agent' in header this is resolved:
```
import requests
import json

r = requests.get('https://www.reddit.com/r/worldnews.json', headers = {'User-agent': 'Chrome'})

theJSON = json.loads(r.text)
print theJSON
```

**Comment by 13steinj** [comment]
AFAIK This is intended. A user agent header is required and default user
agents are not recommended (requests adds a default user agent IIRC).

You also need a *descriptive, non-forged* user agent header (don't lie and
say you are chrome, and be detailed, like "13steinj's mod log scanner
v1.0.0 - requests 2.5.1 - PRAW 3.3.0 - Py3.1").

My guess for the 429 is they've seen a default user agent being used too
many times.

---

On a side note, the github issue panel is for confirmed issues, you are
looking for /r/redditdev / /r/bugs

**Comment by Nikola-K** [comment]
`User-agent` is still defined, it's just that it's by default `"User-Agent": "python-requests/2.8.1"` (varies by requests version) and I assume there are other users running the code with same usr agent value  so reddit simply tells you that the user agent you provided has exceeded the API request limits and returns 429.

**Comment by spladug** [comment]
As mentioned, this is by design and you should 1) include a descriptive user agent, and 2) not forge a browser user agent. See: https://github.com/reddit/reddit/wiki/API#rules
