### ISSUE TITLE
Links from google consistently redirect to home page when on mobile app

### ISSUE THREAD

**Issue by Plasma** [reddit/reddit#1494]
When searching for reddit threads via google, you get to see links like this in search results:

https://m.reddit.com/r/brownman/comments/34fhk6/is_anybody_working_on_a_compilation_of_best_of/

(This is just a random thread I found searching for jibberish)

When you click on it via Chrome in iPhone, you just get redirected to https://m.reddit.com which is obviously super frustrating.

If I click on that link now in a web browser on Chrome deskop it works, but if I reload the page it pushes me back to m.reddit.com too!

If I drop the ``m`` subdomain then the link works always: https://reddit.com/r/brownman/comments/34fhk6/is_anybody_working_on_a_compilation_of_best_of/

**Comment by 13steinj** [comment]
You might have wanted to put this issue in the reddit/reddit-mobile repo instead.

But IIRC it's known, supposed to have been solved before; but still broken.

**Comment by kjoconnor** [comment]
Yep! As 13steinj says the github.com/reddit/reddit-mobile repo is the correct one for this, however they're aware and are working on a fix.

Thanks for reporting!
