### ISSUE TITLE
Running sudo python setup.py build and reciving an error

### ISSUE THREAD

**Issue by BraydonG** [reddit/reddit#1507]
Here is what I did

```
sudo python setup.py build
```
## Code output

```
r2/lib/c/filters.c:24:20: fatal error: Python.h: No such file or directory
compilation terminated.
error: command 'i686-linux-gnu-gcc' failed with exit status 1
```

I can't seem to get reddit running whatsoever probably because I am not running the rest of the code but what is wrong?

**Comment by BraydonG** [comment]
Fixed by installing a missing dependency.

**Comment by Pokechu22** [comment]
FYI `install-reddit.sh` is supposed to automatically handle dependencies and such.

**Comment by BraydonG** [comment]
@Pokechu22 Install-reddit.sh now just contains the words install-reddit.sh or are you talking about the one further in the code?

**Comment by Pokechu22** [comment]
Oh, hm.  I guess they changed it recently.  `install-reddit.sh` is a script that should be runnable to install everything you need - but now it just calls [`reddit.sh` in the install folder](https://github.com/reddit/reddit/blob/master/install/reddit.sh) (which still works).  You should be able to get what you need there.

Alternatively you might want to look at [the install guide](https://github.com/reddit/reddit/wiki/Install-guide).
