### ISSUE TITLE
HTML visible in RSS feed

### ISSUE THREAD

**Issue by testman42** [reddit/reddit#1515]
Since few days ago, I get HTML visible in all of my reddit RSS feeds.
I tried removing the feed and importing it again, but that did not help.
I imported RSS feeds from random subreddits into multiple RSS readers, problem still remains in all scenarios.

For example, [this post](http://www.reddit.com/r/linux/comments/42jbjs/what_open_source_projects_do_you_donate_to/) shows in my RSS feed like this:
```html
<!-- SC_OFF --><div class="md"><p>I try to donate $50-$100 a month to open source software as I use it so much.</p> <p>In the past I&#39;ve donated to:</p> <ul> <li>Keepass</li> <li>Wikipedia</li> <li>Firefox</li> <li>GNOME</li> <li>Latexila (very nice LaTeX editor I&#39;ve combined with R and knittR for dynamic reports)</li> </ul> <p>However I&#39;m sure there are a bunch of key projects that probably get ignored because they don&#39;t operate in the foreground.</p> <p>What open source projects do you donate to?</p> </div><!-- SC_ON -->
```

**Comment by kjoconnor** [comment]
Thanks! This is a [known issue](https://www.reddit.com/r/changelog/comments/428vdq/upcoming_reddit_change_switching_from_rss_20_to/), and should be addressed by us converting feeds to Atom.
