### ISSUE TITLE
Fresh install using script has broken configuration

### ISSUE THREAD

**Issue by CrustyJew** [reddit/reddit#1523]
I just did a fresh install using the automated install script and on trying to connect to the server, it throws an exception

```
reddit/r2/r2/lib/template_helpers.py, line 189:

189  events_collector_key = g.secrets['events_collector_test_js_key']
```

Seems to be related to this https://github.com/reddit/reddit/commit/517a1a49defef86420a41b6d65f1274f83d37 still looking into it and what the deal is.

**Comment by zeantsoi** [comment]
Thanks for pointing this out. We'll push a fix for this, but in the interim, you can circumvent this error by inserting the following values into `example.ini`, probably [here](https://github.com/reddit/reddit/blob/master/r2/example.ini#L49):

    events_collector_test_js_key = 
    events_collector_test_js_secret =

**Comment by CrustyJew** [comment]
Thanks @zeantsoi that fixed it. Also it showed me that I haven't had enough coffee today as I was reading right over the fact that it was looking for _test_ in the key. I was trying to stick in dummy values for the key that already existed there..

**Comment by zeantsoi** [comment]
3e14743ef355fe0ef5fcac336b076f0c924dd120
