### ISSUE TITLE
Migrate from PyCAPTCHA to reCAPTCHA

### ISSUE THREAD

**Issue by spladug** [reddit/reddit#153]
PyCAPTCHA hasn't been updated since 2006.

**Comment by akkatracker** [comment]
@spladug am I right to assume that reCaptcha has been implemented everywhere and this issue can be closed?
![clipboard01](https://cloud.githubusercontent.com/assets/2032746/24345602/a9498f1a-131c-11e7-8fef-fc743dc9a5e0.jpg)

**Comment by spladug** [comment]
Yup!
