### ISSUE TITLE
Easier way to conduct give aways

### ISSUE THREAD

**Issue by christopherwoodall** [reddit/reddit#1541]
An easier method for storing product keys/gift codes and sending them to users would be awesome. You can gift reddit gold, but having the option to gift your own gifts would be great to.  
  
You could submit a csv file with a list of codes. Run a promo or whatever. Users who reply in said thread- or anywhere really- will have an option by their name; ala "Donate". Clicking this will pop a code off the list and send it to the user via DM.

**Comment by kjoconnor** [comment]
This issue tracker is for confirmed bugs only. If you have a feature request or other idea for reddit please post to [r/ideasfortheadmins](https://www.reddit.com/r/ideasfortheadmins).
