### ISSUE TITLE
Why do I get a "400 bad request" every now and then?

### ISSUE THREAD

**Issue by xDinomode** [reddit/reddit#1551]
I've had this happen a few times before. I leave the computer idle for a while, while signed in to Reddit and once I refresh I get a 400 bad request. The way I fix this is by clearing the cache in google chrome. 
Here's a screenshot: [reddit](http://i.imgur.com/cAAONne.png)

**Comment by rram** [comment]
This issue tracker is [only for confirmed bugs.](https://github.com/reddit/reddit/blob/master/CONTRIBUTING.md)

**Comment by xDinomode** [comment]
@rram sorry bout that :)
