### ISSUE TITLE
"Suggest title" broken for specific site, works on others

### ISSUE THREAD

**Issue by ebkalderon** [reddit/reddit#1559]
For some reason, when submitting links to our site (https://www.amethyst.rs/), neither the "suggest title" button nor the thumbnail retrieval works for us. We have tried the following to no avail:

1. Added Open Graph `meta` tags (amethyst/website#41). This got Facebook and most other sites working, but not Reddit.
2. Added more Open Graph tags, tweaked our site to ensure the tags were loaded within the first 1024 bytes of the page, in response to a comment on Reddit issue #55 (amethyst/website#47). This seems to have done nothing.

**Comment by JohannesBeranek** [comment]
@ebkalderon might this be related to https://github.com/reddit/reddit/issues/1438 ?

**Comment by ebkalderon** [comment]
@JohannesBeranek Possibly, but I'm not using Flexible SSL on CloudFlare. I have "Full SSL" enabled instead. I'll be monitoring that issue closely nonetheless, thank you.

**Comment by Blank101** [comment]
A lot of CDNs have a cheaper ssl option of SNI (Server Name Indiciation) which doesn't require a dedicated ip address. The Reddit crawler bot uses Java 6 last time I checked which doesn't support SNI. This can be fixed by updating the crawler bot to Java 7 or using some other library for ssl support. See http://docs.oracle.com/javase/7/docs/technotes/guides/security/enhancements-7.html .

**Comment by kjoconnor** [comment]
This is indeed related to #1438. Thanks for reporting!

**Comment by Blank101** [comment]
I really think this should be looked at. Lots of new websites are using SNI as https picks up steam across the web and not everyone can afford to pay for the $200 or so per month for a dedicated cdn ip. The alternative is that the open graph image tags are not picked up on these sites resulting in lower quality posts.

**Comment by kjoconnor** [comment]
As stated in #1438, we are going to look at it. I don't have a firm date as to when yet, sorry!
