### ISSUE TITLE
No such of file

### ISSUE THREAD

**Issue by adrianevs** [reddit/reddit#1591]
Hello,

I install reddit using the automatic installer but I can't access my installation, but not work redirect to reddit.local but never load. I try to Test the data but after I add "cd $REDDIT_HOME/src/reddit" in terminal I get an error "No such of folder or file"
What's wrong ?

Also the instructions are not very clear.
"1. Get the latest version of the install script"
How to get the latest version is not that made by this line "wget https://raw.github.com/reddit/reddit/master/install-reddit.sh" ?

**Comment by adrianevs** [comment]
Ok, I solve a part a problem, now I populate the script with data but I still have problem to access the instalation.
I access my server ip 129.xxx.xx.xx but has a rediction to reddit.local and looks like load to infinite but never load.

**Comment by adrianevs** [comment]
Some help ?

**Comment by kjoconnor** [comment]
This issue tracker is for confirmed reddit bugs only. If you need help getting your local install working, please post in (r/redditdev)[https://www.reddit.com/r/redditdev].

**Comment by adrianevs** [comment]
I already post there: https://www.reddit.com/r/redditdev/comments/4gnaky/no_such_of_file/ but no one help me.
