### ISSUE TITLE
Setup script exited with error: command 'gcc' failed with exit status 1

### ISSUE THREAD

**Issue by adrianevs** [reddit/reddit#1595]
Hi , I try to install reddit on a 12.04 Ubuntu Server of 8GB RAM.
I install the all dependencies using the PPA but I get an error in the first phrase of the configuration.

Please see the all line from terminal below, The error is in the last line after I add **"sudo python setup.py develop"**

> reddit@dedi-fr-32312:~$ git clone https://github.com/reddit/reddit.git
> Cloning into 'reddit'...
> remote: Counting objects: 68985, done.
> remote: Compressing objects: 100% (11/11), done.
> remote: Total 68985 (delta 1), reused 0 (delta 0), pack-reused 68974
> Receiving objects: 100% (68985/68985), 36.93 MiB | 17.36 MiB/s, done.
> Resolving deltas: 100% (55769/55769), done.
> Checking connectivity... done.
> reddit@dedi-fr-32312:~$ cd reddit/r2
> reddit@dedi-fr-32312:~/reddit/r2$ python setup.py build
> Cannot find Cython. Skipping Cython build.
> Cannot find Baseplate. Skipping Thrift build.
> running build
> running build_py
> creating build
> creating build/lib.linux-x86_64-2.7
> creating build/lib.linux-x86_64-2.7/r2
> copying r2/__init__.py -> build/lib.linux-x86_64-2.7/r2
> copying r2/commands.py -> build/lib.linux-x86_64-2.7/r2
> creating build/lib.linux-x86_64-2.7/r2/lib
> copying r2/lib/hooks.py -> build/lib.linux-x86_64-2.7/r2/lib
> copying r2/lib/eventcollector.py -> build/lib.linux-x86_64-2.7/r2/lib
> copying r2/lib/automoderator.py -> build/lib.linux-x86_64-2.7/r2/lib
> copying r2/lib/cssfilter.py -> build/lib.linux-x86_64-2.7/r2/lib
> copying r2/lib/recommender.py -> build/lib.linux-x86_64-2.7/r2/lib
> copying r2/lib/message_to_email.py -> build/lib.linux-x86_64-2.7/r2/lib
> copying r2/lib/s3_helpers.py -> build/lib.linux-x86_64-2.7/r2/lib
> copying r2/lib/cache_poisoning.py -> build/lib.linux-x86_64-2.7/r2/lib
> copying r2/lib/app_globals.py -> build/lib.linux-x86_64-2.7/r2/lib
> copying r2/lib/butler.py -> build/lib.linux-x86_64-2.7/r2/lib
> copying r2/lib/memoize.py -> build/lib.linux-x86_64-2.7/r2/lib
> copying r2/lib/organic.py -> build/lib.linux-x86_64-2.7/r2/lib
> copying r2/lib/configparse.py -> build/lib.linux-x86_64-2.7/r2/lib
> copying r2/lib/filters.py -> build/lib.linux-x86_64-2.7/r2/lib
> copying r2/lib/inventory_optimization.py -> build/lib.linux-x86_64-2.7/r2/lib
> copying r2/lib/captcha.py -> build/lib.linux-x86_64-2.7/r2/lib
> copying r2/lib/jsonresponse.py -> build/lib.linux-x86_64-2.7/r2/lib
> copying r2/lib/websockets.py -> build/lib.linux-x86_64-2.7/r2/lib
> copying r2/lib/jsontemplates.py -> build/lib.linux-x86_64-2.7/r2/lib
> copying r2/lib/einhorn.py -> build/lib.linux-x86_64-2.7/r2/lib
> copying r2/lib/totp.py -> build/lib.linux-x86_64-2.7/r2/lib
> copying r2/lib/lock.py -> build/lib.linux-x86_64-2.7/r2/lib
> copying r2/lib/inventory.py -> build/lib.linux-x86_64-2.7/r2/lib
> copying r2/lib/ratelimit.py -> build/lib.linux-x86_64-2.7/r2/lib
> copying r2/lib/cookies.py -> build/lib.linux-x86_64-2.7/r2/lib
> copying r2/lib/support_tickets.py -> build/lib.linux-x86_64-2.7/r2/lib
> copying r2/lib/require.py -> build/lib.linux-x86_64-2.7/r2/lib
> copying r2/lib/csrf.py -> build/lib.linux-x86_64-2.7/r2/lib
> copying r2/lib/translation.py -> build/lib.linux-x86_64-2.7/r2/lib
> copying r2/lib/emailer.py -> build/lib.linux-x86_64-2.7/r2/lib
> copying r2/lib/export.py -> build/lib.linux-x86_64-2.7/r2/lib
> copying r2/lib/geoip.py -> build/lib.linux-x86_64-2.7/r2/lib
> copying r2/lib/baseplate_integration.py -> build/lib.linux-x86_64-2.7/r2/lib
> copying r2/lib/strings.py -> build/lib.linux-x86_64-2.7/r2/lib
> copying r2/lib/log.py -> build/lib.linux-x86_64-2.7/r2/lib
> copying r2/lib/merge.py -> build/lib.linux-x86_64-2.7/r2/lib
> copying r2/lib/media.py -> build/lib.linux-x86_64-2.7/r2/lib
> copying r2/lib/static.py -> build/lib.linux-x86_64-2.7/r2/lib
> copying r2/lib/js.py -> build/lib.linux-x86_64-2.7/r2/lib
> copying r2/lib/trending.py -> build/lib.linux-x86_64-2.7/r2/lib
> copying r2/lib/errors.py -> build/lib.linux-x86_64-2.7/r2/lib
> copying r2/lib/language.py -> build/lib.linux-x86_64-2.7/r2/lib
> copying r2/lib/comment_tree.py -> build/lib.linux-x86_64-2.7/r2/lib
> copying r2/lib/sr_pops.py -> build/lib.linux-x86_64-2.7/r2/lib
> copying r2/lib/zookeeper.py -> build/lib.linux-x86_64-2.7/r2/lib
> copying r2/lib/system_messages.py -> build/lib.linux-x86_64-2.7/r2/lib
> copying r2/lib/plugin.py -> build/lib.linux-x86_64-2.7/r2/lib
> copying r2/lib/ip_events.py -> build/lib.linux-x86_64-2.7/r2/lib
> copying r2/lib/normalized_hot.py -> build/lib.linux-x86_64-2.7/r2/lib
> copying r2/lib/embeds.py -> build/lib.linux-x86_64-2.7/r2/lib
> copying r2/lib/promote.py -> build/lib.linux-x86_64-2.7/r2/lib
> copying r2/lib/rising.py -> build/lib.linux-x86_64-2.7/r2/lib
> copying r2/lib/unicode.py -> build/lib.linux-x86_64-2.7/r2/lib
> copying r2/lib/stats.py -> build/lib.linux-x86_64-2.7/r2/lib
> copying r2/lib/mr_top.py -> build/lib.linux-x86_64-2.7/r2/lib
> copying r2/lib/newsletter.py -> build/lib.linux-x86_64-2.7/r2/lib
> copying r2/lib/emr_helpers.py -> build/lib.linux-x86_64-2.7/r2/lib
> copying r2/lib/nymph.py -> build/lib.linux-x86_64-2.7/r2/lib
> copying r2/lib/generate_strings.py -> build/lib.linux-x86_64-2.7/r2/lib
> copying r2/lib/souptest.py -> build/lib.linux-x86_64-2.7/r2/lib
> copying r2/lib/helpers.py -> build/lib.linux-x86_64-2.7/r2/lib
> copying r2/lib/__init__.py -> build/lib.linux-x86_64-2.7/r2/lib
> copying r2/lib/hardcachebackend.py -> build/lib.linux-x86_64-2.7/r2/lib
> copying r2/lib/subreddit_search.py -> build/lib.linux-x86_64-2.7/r2/lib
> copying r2/lib/voting.py -> build/lib.linux-x86_64-2.7/r2/lib
> copying r2/lib/count.py -> build/lib.linux-x86_64-2.7/r2/lib
> copying r2/lib/base.py -> build/lib.linux-x86_64-2.7/r2/lib
> copying r2/lib/template_helpers.py -> build/lib.linux-x86_64-2.7/r2/lib
> copying r2/lib/profiler.py -> build/lib.linux-x86_64-2.7/r2/lib
> copying r2/lib/menus.py -> build/lib.linux-x86_64-2.7/r2/lib
> copying r2/lib/takedowns.py -> build/lib.linux-x86_64-2.7/r2/lib
> copying r2/lib/tracking.py -> build/lib.linux-x86_64-2.7/r2/lib
> copying r2/lib/cache.py -> build/lib.linux-x86_64-2.7/r2/lib
> copying r2/lib/amqp.py -> build/lib.linux-x86_64-2.7/r2/lib
> copying r2/lib/permissions.py -> build/lib.linux-x86_64-2.7/r2/lib
> copying r2/lib/loid.py -> build/lib.linux-x86_64-2.7/r2/lib
> copying r2/lib/gzipper.py -> build/lib.linux-x86_64-2.7/r2/lib
> creating build/lib.linux-x86_64-2.7/r2/templates
> copying r2/templates/__init__.py -> build/lib.linux-x86_64-2.7/r2/templates
> creating build/lib.linux-x86_64-2.7/r2/tests
> copying r2/tests/__init__.py -> build/lib.linux-x86_64-2.7/r2/tests
> creating build/lib.linux-x86_64-2.7/r2/controllers
> copying r2/controllers/errorlog.py -> build/lib.linux-x86_64-2.7/r2/controllers
> copying r2/controllers/multi.py -> build/lib.linux-x86_64-2.7/r2/controllers
> copying r2/controllers/api_docs.py -> build/lib.linux-x86_64-2.7/r2/controllers
> copying r2/controllers/error.py -> build/lib.linux-x86_64-2.7/r2/controllers
> copying r2/controllers/robots.py -> build/lib.linux-x86_64-2.7/r2/controllers
> copying r2/controllers/toolbar.py -> build/lib.linux-x86_64-2.7/r2/controllers
> copying r2/controllers/api.py -> build/lib.linux-x86_64-2.7/r2/controllers
> copying r2/controllers/googletagmanager.py -> build/lib.linux-x86_64-2.7/r2/controllers
> copying r2/controllers/embed.py -> build/lib.linux-x86_64-2.7/r2/controllers
> copying r2/controllers/redirect.py -> build/lib.linux-x86_64-2.7/r2/controllers
> copying r2/controllers/awards.py -> build/lib.linux-x86_64-2.7/r2/controllers
> copying r2/controllers/captcha.py -> build/lib.linux-x86_64-2.7/r2/controllers
> copying r2/controllers/oauth2.py -> build/lib.linux-x86_64-2.7/r2/controllers
> copying r2/controllers/oembed.py -> build/lib.linux-x86_64-2.7/r2/controllers
> copying r2/controllers/health.py -> build/lib.linux-x86_64-2.7/r2/controllers
> copying r2/controllers/buttons.py -> build/lib.linux-x86_64-2.7/r2/controllers
> copying r2/controllers/wiki.py -> build/lib.linux-x86_64-2.7/r2/controllers
> copying r2/controllers/reddit_base.py -> build/lib.linux-x86_64-2.7/r2/controllers
> copying r2/controllers/mailgun.py -> build/lib.linux-x86_64-2.7/r2/controllers
> copying r2/controllers/web.py -> build/lib.linux-x86_64-2.7/r2/controllers
> copying r2/controllers/ipn.py -> build/lib.linux-x86_64-2.7/r2/controllers
> copying r2/controllers/admin.py -> build/lib.linux-x86_64-2.7/r2/controllers
> copying r2/controllers/listingcontroller.py -> build/lib.linux-x86_64-2.7/r2/controllers
> copying r2/controllers/mediaembed.py -> build/lib.linux-x86_64-2.7/r2/controllers
> copying r2/controllers/newsletter.py -> build/lib.linux-x86_64-2.7/r2/controllers
> copying r2/controllers/front.py -> build/lib.linux-x86_64-2.7/r2/controllers
> copying r2/controllers/post.py -> build/lib.linux-x86_64-2.7/r2/controllers
> copying r2/controllers/__init__.py -> build/lib.linux-x86_64-2.7/r2/controllers
> copying r2/controllers/policies.py -> build/lib.linux-x86_64-2.7/r2/controllers
> copying r2/controllers/promotecontroller.py -> build/lib.linux-x86_64-2.7/r2/controllers
> creating build/lib.linux-x86_64-2.7/r2/config
> copying r2/config/hooks.py -> build/lib.linux-x86_64-2.7/r2/config
> copying r2/config/queues.py -> build/lib.linux-x86_64-2.7/r2/config
> copying r2/config/routing.py -> build/lib.linux-x86_64-2.7/r2/config
> copying r2/config/environment.py -> build/lib.linux-x86_64-2.7/r2/config
> copying r2/config/templates.py -> build/lib.linux-x86_64-2.7/r2/config
> copying r2/config/paths.py -> build/lib.linux-x86_64-2.7/r2/config
> copying r2/config/extensions.py -> build/lib.linux-x86_64-2.7/r2/config
> copying r2/config/middleware.py -> build/lib.linux-x86_64-2.7/r2/config
> copying r2/config/__init__.py -> build/lib.linux-x86_64-2.7/r2/config
> creating build/lib.linux-x86_64-2.7/r2/models
> copying r2/models/automoderator.py -> build/lib.linux-x86_64-2.7/r2/models
> copying r2/models/keyvalue.py -> build/lib.linux-x86_64-2.7/r2/models
> copying r2/models/flair.py -> build/lib.linux-x86_64-2.7/r2/models
> copying r2/models/admintools.py -> build/lib.linux-x86_64-2.7/r2/models
> copying r2/models/modaction.py -> build/lib.linux-x86_64-2.7/r2/models
> copying r2/models/builder.py -> build/lib.linux-x86_64-2.7/r2/models
> copying r2/models/subreddit.py -> build/lib.linux-x86_64-2.7/r2/models
> copying r2/models/ip.py -> build/lib.linux-x86_64-2.7/r2/models
> copying r2/models/query_cache.py -> build/lib.linux-x86_64-2.7/r2/models
> copying r2/models/rules.py -> build/lib.linux-x86_64-2.7/r2/models
> copying r2/models/promo_metrics.py -> build/lib.linux-x86_64-2.7/r2/models
> copying r2/models/wiki.py -> build/lib.linux-x86_64-2.7/r2/models
> copying r2/models/bidding.py -> build/lib.linux-x86_64-2.7/r2/models
> copying r2/models/admin_notes.py -> build/lib.linux-x86_64-2.7/r2/models
> copying r2/models/gold.py -> build/lib.linux-x86_64-2.7/r2/models
> copying r2/models/comment_tree.py -> build/lib.linux-x86_64-2.7/r2/models
> copying r2/models/last_modified.py -> build/lib.linux-x86_64-2.7/r2/models
> copying r2/models/link.py -> build/lib.linux-x86_64-2.7/r2/models
> copying r2/models/recommend.py -> build/lib.linux-x86_64-2.7/r2/models
> copying r2/models/promo.py -> build/lib.linux-x86_64-2.7/r2/models
> copying r2/models/bans.py -> build/lib.linux-x86_64-2.7/r2/models
> copying r2/models/award.py -> build/lib.linux-x86_64-2.7/r2/models
> copying r2/models/token.py -> build/lib.linux-x86_64-2.7/r2/models
> copying r2/models/vote.py -> build/lib.linux-x86_64-2.7/r2/models
> copying r2/models/account.py -> build/lib.linux-x86_64-2.7/r2/models
> copying r2/models/trylater.py -> build/lib.linux-x86_64-2.7/r2/models
> copying r2/models/__init__.py -> build/lib.linux-x86_64-2.7/r2/models
> copying r2/models/traffic.py -> build/lib.linux-x86_64-2.7/r2/models
> copying r2/models/mail_queue.py -> build/lib.linux-x86_64-2.7/r2/models
> copying r2/models/report.py -> build/lib.linux-x86_64-2.7/r2/models
> copying r2/models/media_cache.py -> build/lib.linux-x86_64-2.7/r2/models
> copying r2/models/listing.py -> build/lib.linux-x86_64-2.7/r2/models
> copying r2/models/printable.py -> build/lib.linux-x86_64-2.7/r2/models
> creating build/lib.linux-x86_64-2.7/r2/lib/traffic
> copying r2/lib/traffic/emr_traffic.py -> build/lib.linux-x86_64-2.7/r2/lib/traffic
> copying r2/lib/traffic/__init__.py -> build/lib.linux-x86_64-2.7/r2/lib/traffic
> copying r2/lib/traffic/traffic.py -> build/lib.linux-x86_64-2.7/r2/lib/traffic
> creating build/lib.linux-x86_64-2.7/r2/lib/providers
> copying r2/lib/providers/__init__.py -> build/lib.linux-x86_64-2.7/r2/lib/providers
> creating build/lib.linux-x86_64-2.7/r2/lib/migrate
> copying r2/lib/migrate/migrate.py -> build/lib.linux-x86_64-2.7/r2/lib/migrate
> copying r2/lib/migrate/mr_permacache.py -> build/lib.linux-x86_64-2.7/r2/lib/migrate
> copying r2/lib/migrate/vote_details_ip_backfill.py -> build/lib.linux-x86_64-2.7/r2/lib/migrate
> copying r2/lib/migrate/campaigns_to_things.py -> build/lib.linux-x86_64-2.7/r2/lib/migrate
> copying r2/lib/migrate/mr_domains.py -> build/lib.linux-x86_64-2.7/r2/lib/migrate
> copying r2/lib/migrate/__init__.py -> build/lib.linux-x86_64-2.7/r2/lib/migrate
> creating build/lib.linux-x86_64-2.7/r2/lib/db
> copying r2/lib/db/tdb_sql.py -> build/lib.linux-x86_64-2.7/r2/lib/db
> copying r2/lib/db/thing.py -> build/lib.linux-x86_64-2.7/r2/lib/db
> copying r2/lib/db/queries.py -> build/lib.linux-x86_64-2.7/r2/lib/db
> copying r2/lib/db/userrel.py -> build/lib.linux-x86_64-2.7/r2/lib/db
> copying r2/lib/db/operators.py -> build/lib.linux-x86_64-2.7/r2/lib/db
> copying r2/lib/db/tdb_lite.py -> build/lib.linux-x86_64-2.7/r2/lib/db
> copying r2/lib/db/sorts.py -> build/lib.linux-x86_64-2.7/r2/lib/db
> copying r2/lib/db/alter_db.py -> build/lib.linux-x86_64-2.7/r2/lib/db
> copying r2/lib/db/tdb_cassandra.py -> build/lib.linux-x86_64-2.7/r2/lib/db
> copying r2/lib/db/__init__.py -> build/lib.linux-x86_64-2.7/r2/lib/db
> creating build/lib.linux-x86_64-2.7/r2/lib/mr_tools
> copying r2/lib/mr_tools/mr_tools.py -> build/lib.linux-x86_64-2.7/r2/lib/mr_tools
> copying r2/lib/mr_tools/__init__.py -> build/lib.linux-x86_64-2.7/r2/lib/mr_tools
> creating build/lib.linux-x86_64-2.7/r2/lib/contrib
> copying r2/lib/contrib/rcssmin.py -> build/lib.linux-x86_64-2.7/r2/lib/contrib
> copying r2/lib/contrib/ipaddress.py -> build/lib.linux-x86_64-2.7/r2/lib/contrib
> copying r2/lib/contrib/__init__.py -> build/lib.linux-x86_64-2.7/r2/lib/contrib
> creating build/lib.linux-x86_64-2.7/r2/lib/authorize
> copying r2/lib/authorize/api.py -> build/lib.linux-x86_64-2.7/r2/lib/authorize
> copying r2/lib/authorize/interaction.py -> build/lib.linux-x86_64-2.7/r2/lib/authorize
> copying r2/lib/authorize/__init__.py -> build/lib.linux-x86_64-2.7/r2/lib/authorize
> creating build/lib.linux-x86_64-2.7/r2/lib/utils
> copying r2/lib/utils/utils.py -> build/lib.linux-x86_64-2.7/r2/lib/utils
> copying r2/lib/utils/__init__.py -> build/lib.linux-x86_64-2.7/r2/lib/utils
> copying r2/lib/utils/http_utils.py -> build/lib.linux-x86_64-2.7/r2/lib/utils
> creating build/lib.linux-x86_64-2.7/r2/lib/pages
> copying r2/lib/pages/things.py -> build/lib.linux-x86_64-2.7/r2/lib/pages
> copying r2/lib/pages/wiki.py -> build/lib.linux-x86_64-2.7/r2/lib/pages
> copying r2/lib/pages/trafficpages.py -> build/lib.linux-x86_64-2.7/r2/lib/pages
> copying r2/lib/pages/admin_pages.py -> build/lib.linux-x86_64-2.7/r2/lib/pages
> copying r2/lib/pages/pages.py -> build/lib.linux-x86_64-2.7/r2/lib/pages
> copying r2/lib/pages/__init__.py -> build/lib.linux-x86_64-2.7/r2/lib/pages
> creating build/lib.linux-x86_64-2.7/r2/lib/validator
> copying r2/lib/validator/wiki.py -> build/lib.linux-x86_64-2.7/r2/lib/validator
> copying r2/lib/validator/validator.py -> build/lib.linux-x86_64-2.7/r2/lib/validator
> copying r2/lib/validator/__init__.py -> build/lib.linux-x86_64-2.7/r2/lib/validator
> copying r2/lib/validator/preferences.py -> build/lib.linux-x86_64-2.7/r2/lib/validator
> creating build/lib.linux-x86_64-2.7/r2/lib/manager
> copying r2/lib/manager/db_manager.py -> build/lib.linux-x86_64-2.7/r2/lib/manager
> copying r2/lib/manager/__init__.py -> build/lib.linux-x86_64-2.7/r2/lib/manager
> copying r2/lib/manager/tp_manager.py -> build/lib.linux-x86_64-2.7/r2/lib/manager
> creating build/lib.linux-x86_64-2.7/r2/tests/unit
> copying r2/tests/unit/__init__.py -> build/lib.linux-x86_64-2.7/r2/tests/unit
> creating build/lib.linux-x86_64-2.7/r2/tests/functional
> copying r2/tests/functional/__init__.py -> build/lib.linux-x86_64-2.7/r2/tests/functional
> creating build/lib.linux-x86_64-2.7/r2/controllers/apiv1
> copying r2/controllers/apiv1/scopes.py -> build/lib.linux-x86_64-2.7/r2/controllers/apiv1
> copying r2/controllers/apiv1/gold.py -> build/lib.linux-x86_64-2.7/r2/controllers/apiv1
> copying r2/controllers/apiv1/__init__.py -> build/lib.linux-x86_64-2.7/r2/controllers/apiv1
> copying r2/controllers/apiv1/user.py -> build/lib.linux-x86_64-2.7/r2/controllers/apiv1
> creating build/lib.linux-x86_64-2.7/r2/config/feature
> copying r2/config/feature/state.py -> build/lib.linux-x86_64-2.7/r2/config/feature
> copying r2/config/feature/world.py -> build/lib.linux-x86_64-2.7/r2/config/feature
> copying r2/config/feature/__init__.py -> build/lib.linux-x86_64-2.7/r2/config/feature
> copying r2/config/feature/feature.py -> build/lib.linux-x86_64-2.7/r2/config/feature
> creating build/lib.linux-x86_64-2.7/r2/lib/providers/search
> copying r2/lib/providers/search/solr.py -> build/lib.linux-x86_64-2.7/r2/lib/providers/search
> copying r2/lib/providers/search/cloudsearch.py -> build/lib.linux-x86_64-2.7/r2/lib/providers/search
> copying r2/lib/providers/search/__init__.py -> build/lib.linux-x86_64-2.7/r2/lib/providers/search
> copying r2/lib/providers/search/common.py -> build/lib.linux-x86_64-2.7/r2/lib/providers/search
> creating build/lib.linux-x86_64-2.7/r2/lib/providers/support
> copying r2/lib/providers/support/__init__.py -> build/lib.linux-x86_64-2.7/r2/lib/providers/support
> copying r2/lib/providers/support/zendesk.py -> build/lib.linux-x86_64-2.7/r2/lib/providers/support
> creating build/lib.linux-x86_64-2.7/r2/lib/providers/cdn
> copying r2/lib/providers/cdn/cloudflare.py -> build/lib.linux-x86_64-2.7/r2/lib/providers/cdn
> copying r2/lib/providers/cdn/null.py -> build/lib.linux-x86_64-2.7/r2/lib/providers/cdn
> copying r2/lib/providers/cdn/__init__.py -> build/lib.linux-x86_64-2.7/r2/lib/providers/cdn
> creating build/lib.linux-x86_64-2.7/r2/lib/providers/media
> copying r2/lib/providers/media/filesystem.py -> build/lib.linux-x86_64-2.7/r2/lib/providers/media
> copying r2/lib/providers/media/s3.py -> build/lib.linux-x86_64-2.7/r2/lib/providers/media
> copying r2/lib/providers/media/__init__.py -> build/lib.linux-x86_64-2.7/r2/lib/providers/media
> creating build/lib.linux-x86_64-2.7/r2/lib/providers/auth
> copying r2/lib/providers/auth/cookie.py -> build/lib.linux-x86_64-2.7/r2/lib/providers/auth
> copying r2/lib/providers/auth/http.py -> build/lib.linux-x86_64-2.7/r2/lib/providers/auth
> copying r2/lib/providers/auth/__init__.py -> build/lib.linux-x86_64-2.7/r2/lib/providers/auth
> creating build/lib.linux-x86_64-2.7/r2/lib/providers/email
> copying r2/lib/providers/email/null.py -> build/lib.linux-x86_64-2.7/r2/lib/providers/email
> copying r2/lib/providers/email/mailgun.py -> build/lib.linux-x86_64-2.7/r2/lib/providers/email
> copying r2/lib/providers/email/__init__.py -> build/lib.linux-x86_64-2.7/r2/lib/providers/email
> creating build/lib.linux-x86_64-2.7/r2/lib/providers/image_resizing
> copying r2/lib/providers/image_resizing/imgix.py -> build/lib.linux-x86_64-2.7/r2/lib/providers/image_resizing
> copying r2/lib/providers/image_resizing/unsplashit.py -> build/lib.linux-x86_64-2.7/r2/lib/providers/image_resizing
> copying r2/lib/providers/image_resizing/no_op.py -> build/lib.linux-x86_64-2.7/r2/lib/providers/image_resizing
> copying r2/lib/providers/image_resizing/__init__.py -> build/lib.linux-x86_64-2.7/r2/lib/providers/image_resizing
> creating build/lib.linux-x86_64-2.7/r2/tests/unit/lib
> copying r2/tests/unit/lib/souptest_test.py -> build/lib.linux-x86_64-2.7/r2/tests/unit/lib
> copying r2/tests/unit/lib/permissions_test.py -> build/lib.linux-x86_64-2.7/r2/tests/unit/lib
> copying r2/tests/unit/lib/utils_test.py -> build/lib.linux-x86_64-2.7/r2/tests/unit/lib
> copying r2/tests/unit/lib/tracking_test.py -> build/lib.linux-x86_64-2.7/r2/tests/unit/lib
> copying r2/tests/unit/lib/cssfilter_test.py -> build/lib.linux-x86_64-2.7/r2/tests/unit/lib
> copying r2/tests/unit/lib/promote_test.py -> build/lib.linux-x86_64-2.7/r2/tests/unit/lib
> copying r2/tests/unit/lib/stats_test.py -> build/lib.linux-x86_64-2.7/r2/tests/unit/lib
> copying r2/tests/unit/lib/eventcollector_tests.py -> build/lib.linux-x86_64-2.7/r2/tests/unit/lib
> copying r2/tests/unit/lib/media_test.py -> build/lib.linux-x86_64-2.7/r2/tests/unit/lib
> copying r2/tests/unit/lib/__init__.py -> build/lib.linux-x86_64-2.7/r2/tests/unit/lib
> copying r2/tests/unit/lib/urlparser_test.py -> build/lib.linux-x86_64-2.7/r2/tests/unit/lib
> copying r2/tests/unit/lib/cookie_upgrade_test.py -> build/lib.linux-x86_64-2.7/r2/tests/unit/lib
> copying r2/tests/unit/lib/loid_tests.py -> build/lib.linux-x86_64-2.7/r2/tests/unit/lib
> creating build/lib.linux-x86_64-2.7/r2/tests/unit/config
> copying r2/tests/unit/config/experiment_test.py -> build/lib.linux-x86_64-2.7/r2/tests/unit/config
> copying r2/tests/unit/config/__init__.py -> build/lib.linux-x86_64-2.7/r2/tests/unit/config
> copying r2/tests/unit/config/feature_test.py -> build/lib.linux-x86_64-2.7/r2/tests/unit/config
> creating build/lib.linux-x86_64-2.7/r2/tests/unit/models
> copying r2/tests/unit/models/link_test.py -> build/lib.linux-x86_64-2.7/r2/tests/unit/models
> copying r2/tests/unit/models/vote_test.py -> build/lib.linux-x86_64-2.7/r2/tests/unit/models
> copying r2/tests/unit/models/thing_test.py -> build/lib.linux-x86_64-2.7/r2/tests/unit/models
> copying r2/tests/unit/models/subreddit_test.py -> build/lib.linux-x86_64-2.7/r2/tests/unit/models
> copying r2/tests/unit/models/commentbuilder_test.py -> build/lib.linux-x86_64-2.7/r2/tests/unit/models
> copying r2/tests/unit/models/__init__.py -> build/lib.linux-x86_64-2.7/r2/tests/unit/models
> copying r2/tests/unit/models/promo_test.py -> build/lib.linux-x86_64-2.7/r2/tests/unit/models
> creating build/lib.linux-x86_64-2.7/r2/tests/unit/lib/providers
> copying r2/tests/unit/lib/providers/__init__.py -> build/lib.linux-x86_64-2.7/r2/tests/unit/lib/providers
> creating build/lib.linux-x86_64-2.7/r2/tests/unit/lib/authorize
> copying r2/tests/unit/lib/authorize/test_api.py -> build/lib.linux-x86_64-2.7/r2/tests/unit/lib/authorize
> copying r2/tests/unit/lib/authorize/__init__.py -> build/lib.linux-x86_64-2.7/r2/tests/unit/lib/authorize
> copying r2/tests/unit/lib/authorize/test_interaction.py -> build/lib.linux-x86_64-2.7/r2/tests/unit/lib/authorize
> creating build/lib.linux-x86_64-2.7/r2/tests/unit/lib/validator
> copying r2/tests/unit/lib/validator/test_vverifypassword.py -> build/lib.linux-x86_64-2.7/r2/tests/unit/lib/validator
> copying r2/tests/unit/lib/validator/test_validator.py -> build/lib.linux-x86_64-2.7/r2/tests/unit/lib/validator
> copying r2/tests/unit/lib/validator/__init__.py -> build/lib.linux-x86_64-2.7/r2/tests/unit/lib/validator
> creating build/lib.linux-x86_64-2.7/r2/tests/unit/lib/providers/image_resizing
> copying r2/tests/unit/lib/providers/image_resizing/imgix_test.py -> build/lib.linux-x86_64-2.7/r2/tests/unit/lib/providers/image_resizing
> copying r2/tests/unit/lib/providers/image_resizing/unsplashit_test.py -> build/lib.linux-x86_64-2.7/r2/tests/unit/lib/providers/image_resizing
> copying r2/tests/unit/lib/providers/image_resizing/no_op_test.py -> build/lib.linux-x86_64-2.7/r2/tests/unit/lib/providers/image_resizing
> copying r2/tests/unit/lib/providers/image_resizing/__init__.py -> build/lib.linux-x86_64-2.7/r2/tests/unit/lib/providers/image_resizing
> running build_ext
> building 'Cfilters' extension
> creating build/temp.linux-x86_64-2.7
> creating build/temp.linux-x86_64-2.7/r2
> creating build/temp.linux-x86_64-2.7/r2/lib
> creating build/temp.linux-x86_64-2.7/r2/lib/c
> gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c r2/lib/c/filters.c -o build/temp.linux-x86_64-2.7/r2/lib/c/filters.o
> gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro build/temp.linux-x86_64-2.7/r2/lib/c/filters.o -o build/lib.linux-x86_64-2.7/Cfilters.so
> reddit@dedi-fr-32312:~/reddit/r2$ sudo python setup.py develop
> Cannot find Cython. Skipping Cython build.
> Cannot find Baseplate. Skipping Thrift build.
> running develop
> Checking .pth file support in /usr/local/lib/python2.7/dist-packages/
> /usr/bin/python -E -c pass
> TEST PASSED: /usr/local/lib/python2.7/dist-packages/ appears to support .pth files
> running egg_info
> creating r2.egg-info
> writing requirements to r2.egg-info/requires.txt
> writing r2.egg-info/PKG-INFO
> writing top-level names to r2.egg-info/top_level.txt
> writing dependency_links to r2.egg-info/dependency_links.txt
> writing entry points to r2.egg-info/entry_points.txt
> writing manifest file 'r2.egg-info/SOURCES.txt'
> reading manifest file 'r2.egg-info/SOURCES.txt'
> writing manifest file 'r2.egg-info/SOURCES.txt'
> running build_ext
> copying build/lib.linux-x86_64-2.7/Cfilters.so -> 
> Creating /usr/local/lib/python2.7/dist-packages/r2.egg-link (link to .)
> Adding r2 0.0.0dev to easy-install.pth file
> 
> Installed /home/reddit/reddit/r2
> Processing dependencies for r2==0.0.0dev
> Searching for httpagentparser==1.7.8
> Reading http://pypi.python.org/simple/httpagentparser/
> Best match: httpagentparser 1.7.8
> Downloading https://pypi.python.org/packages/3d/1f/0fda47aea1e5498e71deaada625c2c32ef8ddcedb9939280da1e9175c583/httpagentparser-1.7.8.tar.gz#md5=0ca0961b95fc4ec7a20a6b14ebbbe97a
> Processing httpagentparser-1.7.8.tar.gz
> Running httpagentparser-1.7.8/setup.py -q bdist_egg --dist-dir /tmp/easy_install-vNhmtn/httpagentparser-1.7.8/egg-dist-tmp-Y0Hocw
> zip_safe flag not set; analyzing archive contents...
> Adding httpagentparser 1.7.8 to easy-install.pth file
> 
> Installed /usr/local/lib/python2.7/dist-packages/httpagentparser-1.7.8-py2.7.egg
> Searching for python-snappy
> Reading http://pypi.python.org/simple/python-snappy/
> Best match: python-snappy 0.5
> Downloading https://pypi.python.org/packages/70/fa/621594e313b2b9074585af63668f7a31839c4e4d69df536ab592e6e1e353/python-snappy-0.5.tar.gz#md5=044fb0ac21888c0b4eee0c4f15e75504
> Processing python-snappy-0.5.tar.gz
> Running python-snappy-0.5/setup.py -q bdist_egg --dist-dir /tmp/easy_install-TNWEDY/python-snappy-0.5/egg-dist-tmp-M9D6Mz
> cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for Ada/C/ObjC but not for C++ [enabled by default]
> snappymodule.cc:31:22: fatal error: snappy-c.h: No such file or directory
> compilation terminated.
> error: Setup script exited with error: command 'gcc' failed with exit status 1

**Comment by bsimpson63** [comment]
Only Ubuntu 14.04 is supported.

**Comment by puckettgw** [comment]
I get the same problem, and I'm using 14.04:
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c r2/lib/c/filters.c -o build/temp.linux-x86_64-2.7/r2/lib/c/filters.o
x86_64-linux-gnu-gcc: error: r2/lib/c/filters.c: No such file or directory
x86_64-linux-gnu-gcc: fatal error: no input files
