### ISSUE TITLE
PicklingError: Can't pickle <type 'function'>: attribute lookup __builtin__.function failed

### ISSUE THREAD

**Issue by adrianevs** [reddit/reddit#1596]
Hi, I get an error during the installation:

    PicklingError: Can't pickle <type 'function'>: attribute lookup __builtin__.function failed

See the lasts lines from the terminal:

> <type 'exceptions.TypeError'>: 'NoneType' object is not callable
> Exception TypeError: TypeError("'NoneType' object does not support item deletion",) in <Finalize object, dead> ignored
> Adding Pillow 3.2.0 to easy-install.pth file
> Installing explode.py script to /usr/local/bin
> Installing gifmaker.py script to /usr/local/bin
> Installing thresholder.py script to /usr/local/bin
> Installing player.py script to /usr/local/bin
> Installing pilfont.py script to /usr/local/bin
> Installing painter.py script to /usr/local/bin
> Installing viewer.py script to /usr/local/bin
> Installing pilconvert.py script to /usr/local/bin
> Installing pilfile.py script to /usr/local/bin
> Installing enhancer.py script to /usr/local/bin
> Installing pilprint.py script to /usr/local/bin
> Installing pildriver.py script to /usr/local/bin
> Installing createfontdatachunk.py script to /usr/local/bin
> 
> Installed /usr/local/lib/python2.7/dist-packages/Pillow-3.2.0-py2.7-linux-x86_64.egg
> Searching for PyYAML
> Reading http://pypi.python.org/simple/PyYAML/
> Best match: PyYAML 3.11
> Downloading https://pypi.python.org/packages/75/5e/b84feba55e20f8da46ead76f14a3943c8cb722d40360702b2365b91dec00/PyYAML-3.11.tar.gz#md5=f50e08ef0fe55178479d3a618efe21db
> Processing PyYAML-3.11.tar.gz
> Running PyYAML-3.11/setup.py -q bdist_egg --dist-dir /tmp/easy_install-CJANVX/PyYAML-3.11/egg-dist-tmp-bZMb9G
> Building using 4 processes
> Exception in thread Thread-2:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
>     self.run()
>   File "/usr/lib/python2.7/threading.py", line 504, in run
>     self.__target(*self.__args, **self.__kwargs)
>   File "/usr/lib/python2.7/multiprocessing/pool.py", line 319, in _handle_tasks
>     put(task)
> PicklingError: Can't pickle <type 'function'>: attribute lookup __builtin__.function failed

**Comment by bsimpson63** [comment]
What kind of system and environment are you installing reddit on? What install script are you using?
