### ISSUE TITLE
[MAJOR] make: *** [build/public/static/reddit.css] Error 1

### ISSUE THREAD

**Issue by adrianevs** [reddit/reddit#1597]
Hello,

I get an error after $ make line:

Here are the lines from the terminal:

```
reddit@dedi-fr-32312:~/reddit/r2$ make
[+] including definitions from Makefile.py
python setup.py build
Cannot find Baseplate. Skipping Thrift build.
running build
running build_py
running build_ext
python setup.py build_ext --inplace  # copy the .so files from cython into the source tree
Cannot find Baseplate. Skipping Thrift build.
running build_ext
copying build/lib.linux-x86_64-2.7/r2/lib/sgm.so -> r2/lib
copying build/lib.linux-x86_64-2.7/r2/lib/wrapped.so -> r2/lib
copying build/lib.linux-x86_64-2.7/r2/lib/db/_sorts.so -> r2/lib/db
copying build/lib.linux-x86_64-2.7/r2/lib/mr_tools/_mr_tools.so -> r2/lib/mr_tools
copying build/lib.linux-x86_64-2.7/r2/lib/utils/_utils.so -> r2/lib/utils
copying build/lib.linux-x86_64-2.7/r2/lib/utils/comment_tree_utils.so -> r2/lib/utils
copying build/lib.linux-x86_64-2.7/Cfilters.so -> 
# see above
rm -f build/public/static/sprite-reddit.png build/public/static/reddit.css
python r2/lib/nymph.py build/public/static/css/reddit.less build/public/static/sprite-reddit.png > build/public/static/css/reddit.less.tmp
Traceback (most recent call last):
  File "r2/lib/nymph.py", line 185, in <module>
    print spritify(sys.argv[1], sys.argv[2])
  File "r2/lib/nymph.py", line 178, in spritify
    images = _load_spritable_images(css_filename)
  File "r2/lib/nymph.py", line 94, in _load_spritable_images
    image_hash = hashlib.md5(image.convert("RGBA").tostring()).hexdigest()
  File "/usr/local/lib/python2.7/dist-packages/Pillow-3.2.0-py2.7-linux-x86_64.egg/PIL/Image.py", line 699, in tostring
    "Please call tobytes() instead.")
Exception: tostring() has been removed. Please call tobytes() instead.
make: *** [build/public/static/reddit.css] Error 1
reddit@dedi-fr-32312:~/reddit/r2$ sudo apt-get install tobytes
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package tobytes
reddit@dedi-fr-32312:~/reddit/r2$ sudo make clean
[+] including definitions from Makefile.py
rm -f ./r2/lib/sgm.c ./r2/lib/db/_sorts.c ./r2/lib/mr_tools/_mr_tools.c ./r2/lib/wrapped.c ./r2/lib/utils/_utils.c ./r2/lib/utils/comment_tree_utils.c ./r2/lib/sgm.so ./r2/lib/db/_sorts.so ./r2/lib/mr_tools/_mr_tools.so ./r2/lib/wrapped.so ./r2/lib/utils/_utils.so ./r2/lib/utils/comment_tree_utils.so
rm -f r2/lib/generated_strings.py
rm -rf build/static-buildstamp build/public/static  build/mangle-buildstamp
reddit@dedi-fr-32312:~/reddit/r2$ make
[+] including definitions from Makefile.py
python setup.py build
Compiling ./r2/lib/sgm.pyx because it changed.
Compiling ./r2/lib/wrapped.pyx because it changed.
Compiling ./r2/lib/db/_sorts.pyx because it changed.
Compiling ./r2/lib/mr_tools/_mr_tools.pyx because it changed.
Compiling ./r2/lib/utils/_utils.pyx because it changed.
Compiling ./r2/lib/utils/comment_tree_utils.pyx because it changed.
[1/6] Cythonizing ./r2/lib/db/_sorts.pyx
[2/6] Cythonizing ./r2/lib/mr_tools/_mr_tools.pyx
[3/6] Cythonizing ./r2/lib/sgm.pyx
[4/6] Cythonizing ./r2/lib/utils/_utils.pyx
[5/6] Cythonizing ./r2/lib/utils/comment_tree_utils.pyx
[6/6] Cythonizing ./r2/lib/wrapped.pyx
Cannot find Baseplate. Skipping Thrift build.
running build
running build_py
running build_ext
building 'r2.lib.sgm' extension
gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c ./r2/lib/sgm.c -o build/temp.linux-x86_64-2.7/./r2/lib/sgm.o
gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro build/temp.linux-x86_64-2.7/./r2/lib/sgm.o -o build/lib.linux-x86_64-2.7/r2/lib/sgm.so
building 'r2.lib.wrapped' extension
gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c ./r2/lib/wrapped.c -o build/temp.linux-x86_64-2.7/./r2/lib/wrapped.o
gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro build/temp.linux-x86_64-2.7/./r2/lib/wrapped.o -o build/lib.linux-x86_64-2.7/r2/lib/wrapped.so
building 'r2.lib.db._sorts' extension
gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c ./r2/lib/db/_sorts.c -o build/temp.linux-x86_64-2.7/./r2/lib/db/_sorts.o
./r2/lib/db/_sorts.c: In function ‘__pyx_pw_2r2_3lib_2db_6_sorts_15qa’:
./r2/lib/db/_sorts.c:2447:28: warning: ‘__pyx_v_answer_length’ may be used uninitialized in this function [-Wuninitialized]
./r2/lib/db/_sorts.c:2175:14: note: ‘__pyx_v_answer_length’ was declared here
gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro build/temp.linux-x86_64-2.7/./r2/lib/db/_sorts.o -o build/lib.linux-x86_64-2.7/r2/lib/db/_sorts.so
building 'r2.lib.mr_tools._mr_tools' extension
gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c ./r2/lib/mr_tools/_mr_tools.c -o build/temp.linux-x86_64-2.7/./r2/lib/mr_tools/_mr_tools.o
gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro build/temp.linux-x86_64-2.7/./r2/lib/mr_tools/_mr_tools.o -o build/lib.linux-x86_64-2.7/r2/lib/mr_tools/_mr_tools.so
building 'r2.lib.utils._utils' extension
gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c ./r2/lib/utils/_utils.c -o build/temp.linux-x86_64-2.7/./r2/lib/utils/_utils.o
./r2/lib/utils/_utils.c: In function ‘__pyx_f_2r2_3lib_5utils_6_utils_timetext’:
./r2/lib/utils/_utils.c:4235:59: warning: ‘__pyx_v_seconds’ may be used uninitialized in this function [-Wuninitialized]
./r2/lib/utils/_utils.c:9350:34: warning: ‘__pyx_v_i’ may be used uninitialized in this function [-Wuninitialized]
./r2/lib/utils/_utils.c:3695:7: note: ‘__pyx_v_i’ was declared here
gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro build/temp.linux-x86_64-2.7/./r2/lib/utils/_utils.o -o build/lib.linux-x86_64-2.7/r2/lib/utils/_utils.so
building 'r2.lib.utils.comment_tree_utils' extension
gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c ./r2/lib/utils/comment_tree_utils.c -o build/temp.linux-x86_64-2.7/./r2/lib/utils/comment_tree_utils.o
gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro build/temp.linux-x86_64-2.7/./r2/lib/utils/comment_tree_utils.o -o build/lib.linux-x86_64-2.7/r2/lib/utils/comment_tree_utils.so
python setup.py build_ext --inplace  # copy the .so files from cython into the source tree
Cannot find Baseplate. Skipping Thrift build.
running build_ext
copying build/lib.linux-x86_64-2.7/r2/lib/sgm.so -> r2/lib
copying build/lib.linux-x86_64-2.7/r2/lib/wrapped.so -> r2/lib
copying build/lib.linux-x86_64-2.7/r2/lib/db/_sorts.so -> r2/lib/db
copying build/lib.linux-x86_64-2.7/r2/lib/mr_tools/_mr_tools.so -> r2/lib/mr_tools
copying build/lib.linux-x86_64-2.7/r2/lib/utils/_utils.so -> r2/lib/utils
copying build/lib.linux-x86_64-2.7/r2/lib/utils/comment_tree_utils.so -> r2/lib/utils
copying build/lib.linux-x86_64-2.7/Cfilters.so -> 
cp -ruTL r2/public build/public
touch build/static-buildstamp
# see above
rm -f build/public/static/sprite-reddit.png build/public/static/reddit.css
python r2/lib/nymph.py build/public/static/css/reddit.less build/public/static/sprite-reddit.png > build/public/static/css/reddit.less.tmp
Traceback (most recent call last):
  File "r2/lib/nymph.py", line 185, in <module>
    print spritify(sys.argv[1], sys.argv[2])
  File "r2/lib/nymph.py", line 178, in spritify
    images = _load_spritable_images(css_filename)
  File "r2/lib/nymph.py", line 94, in _load_spritable_images
    image_hash = hashlib.md5(image.convert("RGBA").tostring()).hexdigest()
  File "/usr/local/lib/python2.7/dist-packages/Pillow-3.2.0-py2.7-linux-x86_64.egg/PIL/Image.py", line 699, in tostring
    "Please call tobytes() instead.")
Exception: tostring() has been removed. Please call tobytes() instead.
make: *** [build/public/static/reddit.css] Error 1
```

**Comment by adrianevs** [comment]
bump up

**Comment by strix-technica** [comment]
>  File "/usr/local/lib/python2.7/dist-packages/Pillow-3.2.0-py2.7-linux-x86_64.egg/PIL/Image.py", line 699, in tostring
>    "Please call tobytes() instead.")

NB: I'm not a reddit dev nor affiliated with Reddit, Inc. in any way. 

My guess is that you're using a too-recent version of Pillow.  The officially supported/recommended platform is Ubuntu 14.04.  On my box, the version of pillow installed is 2.3.0.  I also note that your Pillow is in /usr/local, implying that you've manually installed this package.  That may be connected to the problem.

Depending on your distro and version, you will have to figure how to get a version of Pillow (and likely other dependencies, IIRC reddit requires a specific version of cassandra) with which reddit is compatible.

**Comment by adrianevs** [comment]
Some help how to install Pillow in the right place ? Thanks.

**Comment by strix-technica** [comment]
It's not the location of Pillow that's the problem, it's the version.  You need to be using the recommended distribution and version (Ubuntu 14.04), or you're pretty much on your own figuring out how to deal with dependency problems.

**Comment by adrianevs** [comment]
Hy, 
I use 12.04 because for 14.04 are missing a lot of dependecies from PPA. Now I delete the actual pillow version and I reinstall 2.0.1 but the error's still there. I will try now with 2.3.0.

**Comment by adrianevs** [comment]
I install Pillow 2.3.0 but now I get another error

```
[+] including definitions from Makefile.py
python setup.py build
Cannot find Baseplate. Skipping Thrift build.
running build
running build_py
running build_ext
python setup.py build_ext --inplace  # copy the .so files from cython into the source tree
Cannot find Baseplate. Skipping Thrift build.
running build_ext
copying build/lib.linux-x86_64-2.7/r2/lib/sgm.so -> r2/lib
copying build/lib.linux-x86_64-2.7/r2/lib/wrapped.so -> r2/lib
copying build/lib.linux-x86_64-2.7/r2/lib/db/_sorts.so -> r2/lib/db
copying build/lib.linux-x86_64-2.7/r2/lib/mr_tools/_mr_tools.so -> r2/lib/mr_tools
copying build/lib.linux-x86_64-2.7/r2/lib/utils/_utils.so -> r2/lib/utils
copying build/lib.linux-x86_64-2.7/r2/lib/utils/comment_tree_utils.so -> r2/lib/utils
copying build/lib.linux-x86_64-2.7/Cfilters.so -> 
# see above
rm -f build/public/static/sprite-reddit.png build/public/static/reddit.css
python r2/lib/nymph.py build/public/static/css/reddit.less build/public/static/sprite-reddit.png > build/public/static/css/reddit.less.tmp
lessc build/public/static/css/reddit.less.tmp > build/public/static/reddit.css.tmp
axconfig: port 1 not active
axconfig: port 2 not active
make: *** [build/public/static/reddit.css] Error 1
```

**Comment by strix-technica** [comment]
> I use 12.04 because for 14.04 are missing

For Reddit?  No.  Have a closer look at the [installer scripts](https://github.com/reddit/reddit/wiki/reddit-install-script-for-Ubuntu).  There are some third party repos involved, but those scripts do the necessary.  Besides, if 14.04 has missing deps, so will 12.04.

Getting a minimally functional reddit is pretty straight forward on a clean machine using that script, provided you follow its instructions (edit `install/install.cfg` with suitable values for reddit user, group and domain!)

I'm afraid that if you can't use the recommended OS/version, then these are the sorts of issues you will have to resolve yourself.  Failing that, spin up a throw-away EC2 instance or similar of Ubuntu 14.04 and try it out for yourself.

**Comment by adrianevs** [comment]
Hi,

I get this errors because I try to do the manual installation. I already tryed the automatic installation but I see that is just for development. After I made the installation I was not able to acces my instalation. Just a reditect at reddit.local.

**Comment by strix-technica** [comment]
I do recommend the automatic installation, even if you hand-hold it and carefully scrutinise the installation script.  That's how I did it (because I've got some rather specific requirements, including not to use HAProxy) and it wasn't that much of a chore.

It's a lot easier to vary the automatic process than it is to do manually, as you'll appreciate if you read through the installer script.

**Comment by adrianevs** [comment]
And what you do after the installation ? At me after the installation I try to acces my server using the ip address 129.xxx.xxx.xxx but it was redirected at "reddit.local".

**Comment by strix-technica** [comment]
> (edit install/install.cfg with suitable values for reddit user, group and domain!)

If you go through example.ini, you will doubtless find stuff you want to change, including the `employees` line (for giving your account admin permissions) .  

Defaults are aimed at developers and performance is therefore terrible, so [enable static CSS/JS](https://www.reddit.com/r/redditdev/comments/2ki4id/turn_off_debug_mode_fresh_install/cllkc1r).  But, beware, [there is a minor-ish bug in respect of these](https://www.reddit.com/r/redditdev/comments/4i6tig/problem_with_static_css_builds_uncompressedjs/).

Don't edit any INI directly.  Edit development.update and execute `make ini`.

**Comment by adrianevs** [comment]
Ok, now I'm lost.
So, you suggest to install reddit using the automatic installer on a 14.04 ubuntu and after that is need to edit install/install.cfg ?
But what is need to edit there ?

**Comment by strix-technica** [comment]
Install.cfg is small and only sets a couple of environment variables.  It'll be obvious enough what to change: which unix user and group do you want to install it as, what domain it will live at.

NB: you have to manually create the unix user and group before you kick off the installer.

**Comment by adrianevs** [comment]
to create unix ? Ok. I think reddit is too complicate for a biginner and instruction are nit complete so I pass. Thanks anyway for help.

**Comment by adrianevs** [comment]
Ok, I try again for the last time. I finish the automatic installation on ubuntu 14.04 and I get this message:

```
Congratulations! reddit is now installed.

The reddit application code is managed with upstart, to see what's currently
running, run

    sudo initctl list | grep reddit

Cron jobs start with "reddit-job-" and queue processors start with
"reddit-consumer-". The crons are managed by /etc/cron.d/reddit. You can
initiate a restart of all the consumers by running:

    sudo reddit-restart

or target specific ones:

    sudo reddit-restart scraper_q

See the GitHub wiki for more information on these jobs:

* https://github.com/reddit/reddit/wiki/Cron-jobs
* https://github.com/reddit/reddit/wiki/Services

The reddit code can be shut down or started up with

    sudo reddit-stop
    sudo reddit-start

And if you think caching might be hurting you, you can flush memcache with

    reddit-flush

Now that the core of reddit is installed, you may want to do some additional
steps:

* Ensure that reddit.local resolves to this machine.

* To populate the database with test data, run:

    cd /home/reddit/src/reddit
    reddit-run scripts/inject_test_data.py -c 'inject_test_data()'

* Manually run reddit-job-update_reddits immediately after populating the db
  or adding your own subreddits.
```

Can help me with nexts ? What should I do now ?

**Comment by strix-technica** [comment]
Reddit is not for the faint of heart, and if you're not a developer or competent Linux admin, you have a steep hill to climb.  As it is, there are a few bugs in the git master/HEAD repository which I'm working on to help fix, but I'm not a reddit dev so obviously it's up to the official devs to decide whether to accept my patches.  

If you are still resolved to proceed, now visit the URL you put into `master.cfg` and see if it works.  Errors will be logged in `/var/syslog`.

Create a reddit account for yourself, edit development.update like this:

    [live_config]
    # permissions! each user should have one of admin, sponsor, or employee as their permission level
    employees = MyUser:admin

then execute `make ini` in the same directory to give yourself admin access.  Go through the rest of `example.ini` to see what else you might want to change.  *Never* edit `development.ini` or `run.ini` directly, always use the `.update; make ini` process.

See my earlier comment for other things you might want to change (re. performance).  Good luck.

**Comment by adrianevs** [comment]
Please help me to eddit install.cfg 

I see that at domain: REDDIT_DOMAIN=${REDDIT_DOMAIN:-reddit.local}
Where exactly I should add my domain ?

**Comment by strix-technica** [comment]
Change the bit that says `reddit.local`.  An IP address may work but it's generally not a good idea to use raw IPs with web servers unless you know what you are doing.

You can either create a DNS record in a domain you already own or, failing that, create an entry in /etc/hosts (unix) or /windows/system32/drivers/etc/hosts (windows) for any domain you like.  Beware that only you will be able to access it.

I hate to say it, but if you can't manage these things on your own, reddit is probably too much for you and you may need to reconsider.  Perhaps a subreddit on reddit.com together with the [reddit widget](https://www.reddit.com/widget) may suffice for your needs.

**Comment by adrianevs** [comment]
Hy,

Thanks for your reply. If I want know all those thing I have to learn it first, right ? 😀 
Thanks for your time :)

**Comment by adrianevs** [comment]
Hy again,

I'm still bit confused about what should add in install.cfg.
The final message of intalation say: Ensure that reddit.local resolves to this machine.
So in this line 
`REDDIT_DOMAIN=${REDDIT_DOMAIN:-reddit.local}`
I should replace "reddit.local" with ip of my server or with the domain ?

REDDIT_DOMAIN=${REDDIT_DOMAIN:-129.xxx.xxx.xxx} or REDDIT_DOMAIN=${REDDIT_DOMAIN:-mywebsite.com} ? or... REDDIT_DOMAIN=${REDDIT_DOMAIN:-127.0.0.1} ??

and after that to point my domain to the server using /etc/hosts or in /etc/resolv.conf.
Right ?

**Comment by strix-technica** [comment]
Yes,
    REDDIT_DOMAIN=${REDDIT_DOMAIN:-129.xxx.xxx.xxx}
    REDDIT_DOMAIN=${REDDIT_DOMAIN:-mywebsite.com}
    REDDIT_DOMAIN=${REDDIT_DOMAIN:-test.subdomain.mywebsite.com}

(the latter being an example of using a subdomain of an existing domain you already own just for testing purposes.)

But again, if this is beyond your level of expertise, you're really going to struggle with post-installation tasks.

**Comment by adrianevs** [comment]
I ask you something and I give you 3 option and you say yes ?
So what I should add there ? Ip address of the server or my domain ?

I know will be hard but how to learn ?

**Comment by adrianevs** [comment]
I think you not got me.

I already connect my domain with my server. But.... When I acces my domain www.mywebsite.com it has a redirection at reddit.local, What should I do to not get the redirection ?

**Comment by strix-technica** [comment]
`install.cfg` determines the initial values with which reddit is configured.

Post installation, configuration is (in the main) controlled by run.ini (aka development.ini).  As I said earlier, never edit these files; instead, edit `development.update` and execute `make ini`.

Which you edit depends on what you're doing and where — reinstalling or tweaking existing install.  Changing the primary domain is not so difficult by editing `development.update`.  Note that there are several instances of the domain there that need to be changed, and also `https_endpoint` if you plan on using SSL.  You can see the possible config options in `example.ini`.  Changing the unix user/group things run as post installation is possible, but harder work (you'd need to go through install/reddit.sh and see where it uses those environment variables).

Look, the Github issue tracker is for developers to discuss bugs demonstrated to exist.  You opened an issue that ultimately turned out to be a local problem (bad version of Pillow) caused by attempting to go at it alone rather than using the automated installer, and without consulting said installer to see what was needed. 

Git issues are not the place to ask for support, particularly not at this remedial level.  It's one thing to ask for some pointers (perhaps /r/redditdev would be a better venue), but you can't expect to have your hand held.  If you can't (or won't) do some leg work on your own to help yourself having been given those pointers, you can expect people to give up in frustration.

**Comment by adrianevs** [comment]
People ask here for support because on /r/redditdev never get help.
Why the guideline not provide this info ?

As per guideline look to be very easy, 3 lines and that's it.
In previous posts you said to chnage the ff line in install.cfg
`REDDIT_DOMAIN=${REDDIT_DOMAIN:-reddit.local}`

You suggest that was needed to be changed before start the installation ? Because not that I understand.

Well, Thanks for your time and sorry for disturbing.
