### ISSUE TITLE
[Image hosting beta] Submit page freezes when you try to submit a link with a ? in it

### ISSUE THREAD

**Issue by rhiever** [reddit/reddit#1609]
Not sure where the best place is to report issues with the new Reddit image hosting service, but I figured here made sense.

If you go to http://reddit.com/r/dataisbeautiful/submit and try to paste a link with a `?` in it (e.g., http://fivethirtyeight.com/features/the-national-parks-have-never-been-more-popular/?ex_cid=538twitter), the page will freeze.

I'm guessing there's some processing going on with links that have a `?` in them that causes this. I was able to reproduce this issue on all subreddits currently in the image hosting beta---even when the subreddit themes were disabled---so this issue doesn't seem to be subreddit-specific.

OS: Mac OS X
Browser: Chrome

**Comment by madbook** [comment]
Hey, thanks for the report.  Looking into it!

**Comment by madbook** [comment]
@rhiever This should be fixed now, would you mind confirming?

**Comment by rhiever** [comment]
Fix confirmed. Thank you for the fast turnaround. 👍
