### ISSUE TITLE
Recent change to the submit form broke POST_submit if the url exists and resubmit is false

### ISSUE THREAD

**Issue by 13steinj** [reddit/reddit#1619]
https://github.com/reddit/reddit/commit/0378c0cbf18722d3e9468e4cbe34ecf0f654e91f has caused the response to be an "errors" array, but without the `form.has_error` line the error itself isn't actually returned.

Relevant praw issue where this was found: https://github.com/praw-dev/praw/issues/611

**Comment by birakattack** [comment]
@13steinj: There is a fix that will be pushed tomorrow for this.

**Comment by 13steinj** [comment]
Thanks :D

**Comment by birakattack** [comment]
@13steinj: The fix was deployed today you can view the commit [here](https://github.com/reddit/reddit/commit/9581950adabcf36fdf8a82d5e4b82d68694a0ea5). Let me know if any issues still persist.
