### ISSUE TITLE
Can't reset password

### ISSUE THREAD

**Issue by diimdeep** [reddit/reddit#1626]
Can't reset password to 'diimdeep' account. 

https://dl.dropboxusercontent.com/u/609809/github.com/reddit%3Areddit/reddit.mov

**Comment by kjoconnor** [comment]
Is there a status code returned for that update password request? Would you be able to check in the network tab on Chrome?

**Comment by diimdeep** [comment]
As far as I understood only single XHR with 200 OK without any kind of redirects, please check it out https://dl.dropboxusercontent.com/u/609809/github.com/reddit%3Areddit/reddit2.mov

**Comment by jackniu1** [comment]
Seems the user 'diimdeep' is Hardbanned, for which status reset password is
not allowed.

Please remove the Hardbanned status first then the user should be able to
reset passwords.

Thanks.

**Comment by diimdeep** [comment]
@kjoconnor  Still can't reset password. Can I have update on this ?

**Comment by kjoconnor** [comment]
Hey! Please email contact@reddit.com and they'll get you squared away. Seems to be an issue with your particular account and not a bug with reddit.
