### ISSUE TITLE
Links no longer open in a new tab.

### ISSUE THREAD

**Issue by Y-Less** [reddit/reddit#1635]
This must be a recent change, because I only noticed it yesterday or the day before.  I have tab-mix-plus set up to open all links to other websites to open in a new tab, which was brilliant for reddit - scroll down the page, click on all the interesting links, then navigate slowly through all the newly opened tabs to view all the content.  I do the same on search engines and any other website with a whole list of links to get through.  However, as of a few days ago, for some reason all the links have started opening in the same tab.  It can't be a plugin issue, because it still works on other sites.  I've inspected the links and the still have the correct `href`, so should work, but I think the issue is something to do with the `data-outbound-url` attribute.

I have found two solutions:

1) Disable JavaScript.  This is the preferred solution once the other site bugs relating to this are fixed.

2) Disable "allow reddit to log my outbound clicks for personalization" in my settings.  This must be a new setting, because I check there quite frequently and have no doubt that if I had seen it before I would have disabled it!  I've also not seen this in any announcements so it seems quite sneaky to put in like that.  This also doesn't solve the problem when I'm not logged in, because there is no disabled setting.

**Comment by umbrae** [comment]
Hey @Y-Less, we posted this recently in our changelog, you can see more here: https://www.reddit.com/r/changelog/comments/4rl5to/outbound_clicks_rollout_complete/

It's not intended to make your extension not work, though. We can look into that to see if it's a general issue, but of course we can't support other extensions.

**Comment by umbrae** [comment]
FYI dug into this, it looks like it's related to how tab mix plus chooses what is "another domain" or not (out.reddit.com is not considered another domain, so keeps it on the same tab). I'd recommend just disabling outbound click events in your preferences for now.

**Comment by Y-Less** [comment]
OK, thanks.  Sorry about not seeing the announcement (I didn't know there was a "changelog" subreddit instead of just the normal announcements).
