### ISSUE TITLE
OAuth API endpoint to get subreddit report reasons

### ISSUE THREAD

**Issue by talklittle** [reddit/reddit#1639]
Currently there is an undocumented API to get the report reasons, but it lacks OAuth support. https://github.com/reddit/reddit/blob/7edd1ec8cd147ba0f71fa9ceaf45706fc869a3ca/r2/r2/controllers/api.py#L5178

Omitting the modhash (which is cookie-login specific) results in a 403 Forbidden response.

It would be great if the endpoint could be updated with OAuth client support.

**Comment by 13steinj** [comment]
Subreddit report reasons are a minified form of their rules, which lies in /r/subname/about/rules.

**Comment by 13steinj** [comment]
Also, to add on, that endpoint that you listed shouldn't cause a 403 unless you are using the client credentials grant: https://github.com/reddit/reddit/blob/36990c40f5410fba2b22fc0bf77db6f24cbd244e/r2/r2/lib/validator/validator.py#L1031 shows that a user authenticated oauth session should still work.

**Comment by talklittle** [comment]
@13steinj Ah, very cool, thanks for the info!
