### ISSUE TITLE
Update to API Wrappers

### ISSUE THREAD

**Issue by CrustyJew** [reddit/reddit#1643]
RedditSharp was marked as unmaintained and the owner refuses to transfer ownership of the repository to anyone to maintain it. I have been removed as a contributor from it and all issues and pull requests were closed.

I've hard forked it as best as GitHub will allow, here https://github.com/CrustyJew/RedditSharp

My Reddit Username is /u/Meepster23

If someone can update the wiki listing for API wrappers so people can find the maintained library, that would be great!

**Comment by 13steinj** [comment]
Might want to ask on the redditdev irc channel (linked on the /r/redditdev sidebar)

**Comment by CrustyJew** [comment]
Good call, I've linked it there
