### ISSUE TITLE
Feature Request: Add omitscript argument to oembed endpoint

### ISSUE THREAD

**Issue by yoshokatana** [reddit/reddit#1645]
Hey all,

First off, congrats on the new oembed endpoint, it works really well!

I was wondering if you're considering adding an `omitscript`/`omit_script` argument to return the embed code without the script? It's handy for CMS developers (like myself) who want to allow our users to embed things easily, and seems to be a pretty solid convention across a number of oembed apis ([Instagram](https://www.instagram.com/developer/embedding/), [Twitter](https://dev.twitter.com/rest/reference/get/statuses/oembed)).

In terms of api response, it would simply remove the script tag, so this:

```json
{
  "provider_url": "https://www.reddit.com/",
  "version": "1.0",
  "author_url": "https://www.reddit.com/user/Viper007Bond",
  "title": "Viper007Bond's comment from discussion \"Devs: reddit now supports oEmbed for comment embeds\"",
  "provider_name": "reddit",
  "type": "rich",
  "html": "<div class=\"reddit-embed\" data-embed-media=\"www.redditmedia.com\" data-embed-parent=\"false\" data-embed-live=\"false\" data-embed-uuid=\"17433fa0-4944-11e6-b462-0ed39e408755\" data-embed-created=\"2016-07-13T21:52:27.720982+00:00\"><a href=\"https://www.reddit.com/r/redditdev/comments/34c0pm/devs_reddit_now_supports_oembed_for_comment_embeds/cqtl26d\">Comment</a> from discussion <a href=\"https://www.reddit.com/r/redditdev/comments/34c0pm/devs_reddit_now_supports_oembed_for_comment_embeds/\">Viper007Bond's comment from discussion &quot;Devs: reddit now supports oEmbed for comment embeds&quot;</a>.</div><script async src="https://www.redditstatic.com/comment-embed.js"></script>",
  "author_name": "Viper007Bond"
}
```

would simply change to this:

```json
{
  "provider_url": "https://www.reddit.com/",
  "version": "1.0",
  "author_url": "https://www.reddit.com/user/Viper007Bond",
  "title": "Viper007Bond's comment from discussion \"Devs: reddit now supports oEmbed for comment embeds\"",
  "provider_name": "reddit",
  "type": "rich",
  "html": "<div class=\"reddit-embed\" data-embed-media=\"www.redditmedia.com\" data-embed-parent=\"false\" data-embed-live=\"false\" data-embed-uuid=\"17433fa0-4944-11e6-b462-0ed39e408755\" data-embed-created=\"2016-07-13T21:52:27.720982+00:00\"><a href=\"https://www.reddit.com/r/redditdev/comments/34c0pm/devs_reddit_now_supports_oembed_for_comment_embeds/cqtl26d\">Comment</a> from discussion <a href=\"https://www.reddit.com/r/redditdev/comments/34c0pm/devs_reddit_now_supports_oembed_for_comment_embeds/\">Viper007Bond's comment from discussion &quot;Devs: reddit now supports oEmbed for comment embeds&quot;</a>.</div>",
  "author_name": "Viper007Bond"
}
```

Thoughts?

**Comment by 13steinj** [comment]
*New*? I don't remember anything with oembed recently.

However, see https://github.com/reddit/reddit/blob/master/CONTRIBUTING.md

> Don't use GitHub issues for feature requests. If you have a feature request, please submit it to /r/ideasfortheadmins instead. Please note that while we do subscribe to /r/ideasfortheadmins, the presence of a response or lack thereof has no indication as to whether the idea will actually get implemented.

Though you may want to also submit to /r/redditdev

**Comment by yoshokatana** [comment]
Ah! I didn't see that. I'll go there instead 😄

**Comment by yoshokatana** [comment]
Submitted to [/r/redditdev](https://www.reddit.com/r/redditdev/comments/4stlsl/feature_request_add_omitscript_argument_to_oembed/)
