### ISSUE TITLE
API for promoted Live thread

### ISSUE THREAD

**Issue by Nxt3** [reddit/reddit#1654]
Would be great for devs to be able to get the current "trending/popular" live thread that shows up on your frontpage if you're on a desktop. Currently, the only real way to get that is from the HTML Reddit desktop response.

For example, I never would have seen the thread about the Munich shootings if I wasn't on desktop.

**Comment by 13steinj** [comment]
Oh, didn't know an api didn't exist for it. I'll make a pr for it on the weekend (but in the reddit live repo, not this one).

**Comment by 13steinj** [comment]
There, made :)

**Comment by Nxt3** [comment]
You da bomb. Thank you. :D

**Comment by 13steinj** [comment]
This can be safely closed now.
