### ISSUE TITLE
Highlight comments added from previous read post

### ISSUE THREAD

**Issue by kostya** [reddit/reddit#1658]
Right now is hard to find new comments in all trees (?sort=new, not really helps), would be nice if new comments hightlighted to easier find it.

**Comment by 13steinj** [comment]
This is a gold feature.

**Comment by kjoconnor** [comment]
From the [issue guidelines](https://github.com/reddit/reddit#issues-and-contribution-guidelines):
> First things first, though: github issues is only for confirmed, active bugs. Please submit ideas to [/r/ideasfortheadmins](https://www.reddit.com/r/ideasfortheadmins).

(and also yes, this is a gold feature.)
