### ISSUE TITLE
Score value for an archived post changes on page refresh

### ISSUE THREAD

**Issue by dandelionred** [reddit/reddit#1663]
Here is a sample post https://www.reddit.com/r/pcmasterrace/comments/2qys7c/happy_new_year_brethren/

It was created on Thu Jan  1 00:00:02 UTC 2015 so it was archived long ago.

When I consecutively update the page the score shown is one of 1, 2, 3, 4, 5. The same happens when fetching the post with `api/info`.

Another sample (same creation time) https://www.reddit.com/r/gopro/comments/2qys7e/took_this_shot_up_in_northern_california_with_my/
Score shown is one of 26, 27, 28, 29.

In case it is not a bug in caching or something, is there a way to get real scores?

**Comment by umbrae** [comment]
This is due to fuzzing, an anti cheating technique. Sorry, there's no way to get the real score.

**Comment by dandelionred** [comment]
Can you please give me a hint what is the idea behind score fuzzying for **archived** posts?
