### ISSUE TITLE
UI - Infinity Scroll

### ISSUE THREAD

**Issue by augustnmonteiro** [reddit/reddit#1665]
Create Infinity scroll feature.

Pros:
   reduce data transfer

Cons:
   ads

**Comment by lucasmorano** [comment]
That would be awesome

**Comment by kjoconnor** [comment]
From our [Issue Guidelines](https://github.com/reddit/reddit#issues-and-contribution-guidelines):

> Thanks for wanting to help make reddit better! First things first, though: github issues is only for confirmed, active bugs. Please submit ideas to [/r/ideasfortheadmins](https://www.reddit.com/r/ideasfortheadmins).

**Comment by augustnmonteiro** [comment]
Thanks :D
