### ISSUE TITLE
[Feature request] Reprioritizing subbreddits in your frontpage

### ISSUE THREAD

**Issue by Aevann** [reddit/reddit#1667]
As a reddit user, sometimes you subscribe to a subreddit and then find it appearing in your frontpage much more frequently / much less frequently than you would like...

So I don't know if the current reddit algorithm permits this or not but here is my suggestion :
a user interface for changing subreddits rate of appearing in one's frontpage.

let's say I subscribed to r/tech and found it appearing way less frequently than I would like.
I go to that reprioritizing interface and here's what I see
> r/tech presence in your frontpage
> ☐ More frequent
> ☑ Current rate
> ☐ Less frequent

I click 'More frequent' and voila, I get to see tech news more now.

Is that feasible ?

**Comment by kjoconnor** [comment]
From our [Issue Guidelines](https://github.com/reddit/reddit#issues-and-contribution-guidelines):

> Thanks for wanting to help make reddit better! First things first, though: github issues is only for confirmed, active bugs. Please submit ideas to [/r/ideasfortheadmins](https://www.reddit.com/r/ideasfortheadmins).
