### ISSUE TITLE
Comment history missing

### ISSUE THREAD

**Issue by tchoulihan** [reddit/reddit#1680]
I'm using the endpoint `/user/xxx/comments.json` to do an export of my comment history, paging using after, with a limit of 100. 

Using the default sort of new, I find that it only gets comments from up to a few months back, until after becomes "null". 

I notice that if I sort by top, or new, I get different results that aren't contained in the other export. 

Why isn't this endpoint paging through my whole history correctly?

**Comment by kjoconnor** [comment]
Looks like this was explained [here](https://www.reddit.com/r/bugs/comments/50jiyi/comment_history_is_missing/d74pjpw?context=3).
