### ISSUE TITLE
Custom sort

### ISSUE THREAD

**Issue by svnpenn** [reddit/reddit#1695]
CloudSearch certainly supports custom sorting, but it seems it cannot be accessed through Reddit:

http://reddit.com/search?syntax=cloudsearch&q=cats&sort=flair_text

Please advise if my syntax is wrong, thank you.

**Comment by 13steinj** [comment]
The sort parameter is used by reddit itself and presumably alters it to be used in cloudsearch. Only relevance, relevance2, top, new, and hot iirc are valid. If you want to be able to use custom fields, you should ask on /r/ideasfortheadmins

**Comment by madbook** [comment]
Yup! I think that would fall under "feature request".  Going to go ahead and close this for now.  Thanks!
