### ISSUE TITLE
Reddit's submission should check both https and http for duplicate URLs.

### ISSUE THREAD

**Issue by antdude** [reddit/reddit#1696]
For an example:
https://www.youtube.com/watch?v=ZgJyhKEZ8QU
http://www.youtube.com/watch?v=ZgJyhKEZ8QU

Reddit think these are different URLs when submitting. Thank you in advance. :)

**Comment by madbook** [comment]
Thanks for bringing this up! This isn't really a bug – technically they are different.  It might be a nice enhancement, but we're probably not going to get to it any time soon.  I'm going to go ahead and close this for now.
