### ISSUE TITLE
Create Account: Not working !

### ISSUE THREAD

**Issue by TriMoon** [reddit/reddit#1699]
I'm using FF-DevEdition on Win10.
No matter what i try i'm unable to create an account.
I just fill in username, 2x password, email.

The error given back is only "care to try these again?" in red.
I'm not blocking anything.

**Comment by kjoconnor** [comment]
This issue tracker is for confirmed bugs only. Do you mind heading over to https://www.reddit.com/r/help or https://www.reddit.com/r/bugs and posting there first?

Thanks!
