### ISSUE TITLE
No fallback when JavaScript is disabled.

### ISSUE THREAD

**Issue by Y-Less** [reddit/reddit#1704]
This is entirely a duplicate of #1350 which was closed with talk of revisiting it at a later date.  I posted in there almost two months ago for a reopening since I can't do it myself, but with no reply hence this new issue.  The original issue:

> It is impossible to post a comment, or even view some comments, with JavaScript disabled via the likes of NoScript. This seems like a massive oversight given that they should only require basic tags that are a basic part of HTML.

The revisiting mention:

> fwiw, we're currently rebuilding mobile web in such a way that most, if not all, of the functionality works with javascript disabled; we expect that work to be live in a couple months, maybe sooner. That technology will almost certainly make its way back to desktop, although it'll be some time before it's implemented. Closing this for now.

**Comment by ajacksified** [comment]
The team has decided that the use-case for no js is too small to be worth the complexity. This was not my decision, but it is unlikely that the no-js use case will be resolved. The site will remain readable, but not interactable, for the foreseeable future.

**Comment by 13steinj** [comment]
> fwiw, we're currently rebuilding mobile web in such a way that most, if not all, of the functionality works with javascript disabled; we expect that work to be live in a couple months, maybe sooner. That technology will almost certainly make its way back to desktop, although it'll be some time before it's implemented

Your decision or not, I must say it's somewhat of a surprising 180 stance on the concern.

**Comment by Y-Less** [comment]
Can I ask why?  It seems a very odd position to not support progressive enhancements properly while purporting to be "the front page of the internet".  And since 99% of what you do is links and text input, which can be fully achieved with `<a>` and `<input>` there is no need for JS in the first place beyond maybe some silly extra gold features.
