### ISSUE TITLE
Cannot view parent comment in reply to inbox

### ISSUE THREAD

**Issue by PokestarFan** [reddit/reddit#1715]
Of that sounds confusing, just visit [https://www.reddit.com/r/bugs/comments/58yme3/unable_to_load_parent_comment_in_inbox/?st=iupujggd&sh=e0019d69]

**Comment by telaviv** [comment]
Thanks @PokestarFan for the patch! Unfortunately the break that you're fixing isn't quite open source yet so this wouldn't actually fix things there. In addition if you test reddit now, you'll see that the issue has already been pushed on the closed source version. The open source trailing slash change will make it to Open Source this week though.
