### ISSUE TITLE
Subreddit titlebox covers "my subreddits" dropdown

### ISSUE THREAD

**Issue by kamilogorek** [reddit/reddit#1726]
Hey!

Quick writeup.

Broken:
<img width="335" alt="screen shot 2016-11-09 at 15 09 59" src="https://cloud.githubusercontent.com/assets/1523305/20141053/e4a070f6-a68e-11e6-81e5-4753e1c7f1c2.png">

Fixed:
<img width="345" alt="screen shot 2016-11-09 at 15 09 47" src="https://cloud.githubusercontent.com/assets/1523305/20141054/e5d960b8-a68e-11e6-9e96-6b712849f831.png">

Fix:

Change:
```
#header {
  z-index: 99;
}
```

to:

```
#header {
  z-index: 103; // or higher
}
```

Cheers!

**Comment by 13steinj** [comment]
Not a reddit problem, you have to message the mods of that sub

**Comment by kamilogorek** [comment]
Thanks @13steinj, forwarded the issue to moderators.

Cheers!
