### ISSUE TITLE
Proposed addition of graw to API wrapper list.

### ISSUE THREAD

**Issue by turnage** [reddit/reddit#1737]
I wasn't sure how to propose graw be added; my apologies if a github issue is not the appropriate way.

I recently stabilized the API for graw, a Reddit bot library, and it would be awesome to get a listing on the [API wrapper wiki page](https://github.com/reddit/reddit/wiki/API-Wrappers) in this repo. It may not be right for it though because it doesn't just wrap the API. The API wrapper which includes some endpoints is in [this package](https://godoc.org/github.com/turnage/graw/reddit), and graw itself abstracts the API away and just connects bots to event streams on Reddit (e.g. a user specifies they want to process all new posts /r/subreddit, and graw feeds them the new posts).

This is the information other wrappers have in the table, about graw:
* [Repo link](https://github.com/turnage/graw)
* It supports OAuth2
* The API is stable
* The author's (my) username is /u/roxven
* It is implemented in Go
* The license is MIT

**Comment by kjoconnor** [comment]
Cool! Thanks for writing & maintaining it. I'll add it now.
