### ISSUE TITLE
OAuth2 Error  Too Many Requests (RFC 6585) (HTTP 429). Failed to get an access token in R studio

### ISSUE THREAD

**Issue by mikeyrocks11** [reddit/reddit#1738]
Hello,

I am trying to get a oauth2 authorization for R studio, I have followed the API documentation as closely as I could for R. I am getting an issue when I am running the `oauth2.0_token` function. I run the code with the correct args and then takes me to my browser to ask authorization for request to connect with your reddit account 'Allow' or 'Decline' . Click allow and go back to R with this error message: 

`Authentication complete.`
`Error in init_oauth2.0(self$endpoint, self$app, scope = self$params$scope,  : `
  `Too Many Requests (RFC 6585) (HTTP 429). Failed to get an access token.`

Anyone that has set up reddit API through R please help?

**Comment by kjoconnor** [comment]
Hello there!

This issue tracker is only for confirmed, active bugs. If you need help accessing the API or working through rate limits, please post in [r/redditdev](https://www.reddit.com/r/redditdev).
