### ISSUE TITLE
fatal: Could not change back to '/root': Permission denied

### ISSUE THREAD

**Issue by Hostile** [reddit/reddit#1743]
at the end i got 
    fatal: Could not change back to '/root': Permission denied

how to fix it? ubuntu 14.04

**Comment by kjoconnor** [comment]
This issue tracker is for [confirmed, active bugs](https://github.com/reddit/reddit#issues-and-contribution-guidelines) only. For issues with getting the VM running, etc., please head over to [r/redditdev](https://www.reddit.com/r/redditdev).

**Comment by Hostile** [comment]
I am getting this error on fresh Ubuntu

and I am running install script https://github.com/reddit/reddit/wiki/reddit-install-script-for-Ubuntu

it goes almost to end but at the end there is above error. Its not VM prob i guess.
