### ISSUE TITLE
Update PRAW licence in /wiki/API-Wrappers

### ISSUE THREAD

**Issue by agsimmons** [reddit/reddit#1757]
PRAW changed their license from GPL v3 to BSD 2-Clause on 2016-08-15. This should be reflected in the wiki page on Reddit API wrappers. As far as I know, I can't create a pull request for a wiki page, otherwise I would modify it myself.

Full wiki page URL: https://github.com/reddit/reddit/wiki/API-Wrappers

**Comment by andytuba** [comment]
https://github.com/reddit/reddit/wiki/API-Wrappers/89ca580b1ec02c13bc8983a30daa557fbc86f93c

Thanks for highlighting that!
