### ISSUE TITLE
"502ssl" error when opening parent link

### ISSUE THREAD

**Issue by ahiskali** [reddit/reddit#1763]
[This](https://www.reddit.com/r/comics/comments/4p6fny/help_daddy/d4ip736/) comment's parent gives the error.
It works if you delete parameters after the question mark.

**Comment by kjoconnor** [comment]
From our [contributing guidelines](https://github.com/reddit/reddit/blob/master/CONTRIBUTING.md):

> Don't submit unconfirmed bugs. Please make sure your bug is an actual bug before reporting it. Unfortunately, things will sometimes break on the operations side of the site (e.g. a database slowing down, or a server being unavailable). These issues may look like a bug, but they are not. If you're not sure, make a post in /r/bugs.

Thanks for reporting.
