### ISSUE TITLE
All the things are a thing.

### ISSUE THREAD

**Issue by RheaAyase** [reddit/reddit#1765]
I would like to point out how obscure the naming scheme is. I find this to be a sin against any kind of programming - especially the Object Oriented kind. Think about throwing this change in, for next major and breaking API release :)

_Not meant as sarcasm or joke, deadly serious here. The naming could use a bit of work... And I'm surprised I didn't find similar issue created yet. All hope for humanity is at stake here._

**Comment by kjoconnor** [comment]
There's no*thing* wrong with every*thing* being a *thing*, unless you make it a *thing*. Having *thing*s just be *thing*s makes it easy to work on new *thing*s. I don't understand where the confusion could be!

Just kidding. While the naming might be slightly confusing, in practice it ends up fine and we're a bit too far out to be making sweeping data model changes at this point. Thanks for the suggestion!

**Comment by RheaAyase** [comment]
> There's nothing wrong with everything being a thing, unless you make it a thing. Having things just be things makes it easy to work on new things. I don't understand where the confusion could be!

:D <3

> Just kidding. While the naming might be slightly confusing, in practice it ends up fine and we're a bit too far out to be making sweeping data model changes at this point. Thanks for the suggestion!

I know, I had to try...
