### ISSUE TITLE
Bad x-posted title parsing

### ISSUE THREAD

**Issue by vaindil** [reddit/reddit#1774]
[This post](https://www.reddit.com/r/HistoryPorn/comments/5zbz3l/wilt_chamberlain_demonstrates_his_reach_to/) shows as x-posted from /r/1162, but that sub doesn't exist. Looks like it parsed `X 1162]` incorrectly.

**Comment by Pokechu22** [comment]
Reddit itself doesn't do any x-post parsing as far as I know (though it does have "other discussions", that isn't based off of the title).  Is this from an app?

**Comment by vaindil** [comment]
Oh, looks like it's actually an RES thing, didn't even think to check that. My apologies!

**Comment by andytuba** [comment]
RES doesn't bother with validating if the subreddit exists, it just trusts that the user put something vaguely correct in the title.
