### ISSUE TITLE
Unable to reset password

### ISSUE THREAD

**Issue by agm1984** [reddit/reddit#1784]
I've been trying for about a year now to reset my password. It's kind of ridiculous because it's the same problem no matter what computer I use or mobile device. I've tried it on about 6 different workstations and 10 or 20 different mobile browsers (because I do QA professionally).

I am able to receive the Forgot Password email, and when I type a new password and hit 'submit', it just shows "Submitting..." then disappears and nothing. If I press submit again after seemingly any period of time, it says the password reset link has expired. I can repeat this process ad infinitum. (no errors in console, etc. it seems to just submit to a black hole with terrible UX).

To reproduce:
1) Navigate to www.reddit.com
2) Hit reset password
3) Enter username (in my case, agm1984)
4) Check email, open email from Reddit
5) Hit password reset link in email
6) Type a new password
7) Confirm it
8) Press Submit

Actual results: nothing happens other than text flashing up for a fraction of a second, "Submitting..."

Expected results: Success or failure message should be displayed. User should be able to login with the password they just specified and submitted.

**Comment by kjoconnor** [comment]
Hello! Can you please get in touch with us at contact@reddit.com so we can get some more info to try and help you reset this?

Thanks!
