### ISSUE TITLE
Reddit homepage served using HTTP/1.0

### ISSUE THREAD

**Issue by ravinet** [reddit/reddit#1790]
Is there a way to change this to use HTTP/1.1?

**Comment by kjoconnor** [comment]
Not sure what you mean, we definitely support HTTP/1.1 and HTTP2.

https://www.webpagetest.org/result/170409_XV_60B/1/details/#step1_request2

**Comment by ravinet** [comment]
Thank you for the response, and sorry for not providing enough detail with the question. I am setting up my own reddit clone and the url http://reddit.local is served using HTTP/1.0. Other URLs (e.g., reddit.local/media/*) are served using HTTP/1.1. Also, https://reddit.local is served using HTTP/1.1. I realize that the real reddit site (https://reddit.com) uses HTTPS, but it would be helpful for me to be able to load http://reddit.local with HTTP/1.0.

I tried to locate where the Paste WSGI HTTP server is configured, but it seems nested in the pylons make_app logic. Is there a way to configure it such that all URLs are served using HTTP/1.1?

Thanks!
