### ISSUE TITLE
Python-snappy module can't be installed during reddit/r2/setup.py develop command

### ISSUE THREAD

**Issue by HamishWHC** [reddit/reddit#1811]
Not sure if this is where I should be posting, I'm very new to Github.

During reddit installation, running the command:

`sudo python setup.py develop`

This results in an error relating to python-snappy, saying that a file does not exist and cannot be run. I have tried forcing the script to dowload a previous version, however it returns the same error. I have thought of trying to install reddit and simply removing this from the script so it doesn't try to install it. Will doing this result in major problems and what is python-snappy used for in the code?

**Comment by DarkWorld25** [comment]
UPDATE: This is while installing reddit via the install script on Ubuntu 16.04

**Comment by HamishWHC** [comment]
Solved: Snappy C Library not installed.

**Comment by HamishWHC** [comment]
And not with the install script.
