### ISSUE TITLE
Long links break new profile UI

### ISSUE THREAD

**Issue by Isinlor** [reddit/reddit#1814]
Long links in comments stretch out horizontally the view area in the new profile to the point where it becomes not usable. Example: https://www.reddit.com/user/isinlor/comments/

Removing `word-break: keep-all;` form `.StyledHtml p` solves the issue.

**Comment by justcool393** [comment]
Not reddit staff, but this is probably suited better for /r/beta.

**Comment by Isinlor** [comment]
Seems to be fixed.
