### ISSUE TITLE
Hard to find issue tracker from reddit.com

### ISSUE THREAD

**Issue by 0joshuaolson1** [reddit/reddit#1826]
It's not at the bottom of the main page, and it's not in the wiki as far as I looked.

**Comment by 13steinj** [comment]
If by issue tracker you mean this issue tracker, it's meant to be hard to find, as this should only be used for confirmed bugs / server side only bugs that most people either can't confirm or won't run into. /r/bugs is to be used for possible bug reports otherwise.

**Comment by 0joshuaolson1** [comment]
[Okay.](https://www.reddit.com/r/bugs/comments/6m8h54/comment_count_for_a_post_higher_than_the_number/)
