### ISSUE TITLE
Give the user an explanation instead of an error status code

### ISSUE THREAD

**Issue by nazarimilad** [reddit/reddit#1829]
### How to reproduce this error:

1. Have two browser tabs open, with both being on Reddit, not logged in
2. Log in on the first Reddit tab with one account. Wait until you're logged in.
3. Try to log in on the second tab with another Reddit account (without refreshing any page)

On this second page an error will appear under the username and password fiels in red:
"an error occurred (status: 409)".

![image](https://user-images.githubusercontent.com/23218676/28288052-2a8a12ce-6b3e-11e7-9cf8-8939c070d128.png)

### What I suggest
Is it possible to give the user an explanation instead of just an error code? For example
"You seem to be already logged in with a different account. Refresh this page."

**Comment by bershan2** [comment]
@nazarimilad This is not really a bug, this is more an improvement idea. I'm not sure, but I think, according to [CONTRIBUTING](https://github.com/reddit/reddit/blob/master/CONTRIBUTING.md) this should be posted in [/r/ideasfortheadmins](http://www.reddit.com/r/ideasfortheadmins):
>Don't use GitHub issues for feature requests. If you have a feature request, please submit it to /r/ideasfortheadmins instead. Please note that while we do subscribe to /r/ideasfortheadmins, the presence of a response or lack thereof has no indication as to whether the idea will actually get implemented.

**Comment by nazarimilad** [comment]
I see, I will post it there then.
