### ISSUE TITLE
each time I run make, I get a different error

### ISSUE THREAD

**Issue by rsd** [reddit/reddit#1836]
~/reddit/r2$ make
,,,
python r2/lib/js.py build_module "reddit-embed"
Compiling reddit-embed.js...Traceback (most recent call last):
  File "r2/lib/js.py", line 809, in <module>
...
~/reddit/r2$ make
,,,
python r2/lib/js.py build_module "timeseries"
Compiling timeseries.js...Traceback (most recent call last):
...

So, the next make run, it just ignores the previous error, until it completly fail.
I can make clean to start over.

Some of them are node modules, but even installing with npm install -g, the makefile does not use it.

Also, I have no idea where to get modtools.js.  It is not a nodejs module.

What should I do?

**Comment by 13steinj** [comment]
I'd be happy to help if you post the full traceback and if your install is up to date or not.

**Comment by rsd** [comment]
It's Ubuntu 14.04 as the document suggests.
I tried stretch and 16.04 and 14.04 is the one I got farthest.

It is full updated (as possible), using reddit's PPA and python 2.7.12 (as 2.7.5 has SSL problems).

here is the full log:
```
Script started on Thu 03 Aug 2017 12:27:55 AM UTC
reddit@reddit:~/reddit/r2$ make
[+] including definitions from Makefile.py
python setup.py build
Cannot find Baseplate. Skipping Thrift build.
/usr/local/lib/python2.7/dist-packages/setuptools/dist.py:350: UserWarning: The version specified ('') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
  "details." % self.metadata.version
running build
running build_py
running build_ext
python setup.py build_ext --inplace  # copy the .so files from cython into the source tree
Cannot find Baseplate. Skipping Thrift build.
/usr/local/lib/python2.7/dist-packages/setuptools/dist.py:350: UserWarning: The version specified ('') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
  "details." % self.metadata.version
running build_ext
copying build/lib.linux-x86_64-2.7/r2/lib/wrapped.so -> r2/lib
copying build/lib.linux-x86_64-2.7/r2/lib/sgm.so -> r2/lib
copying build/lib.linux-x86_64-2.7/r2/lib/utils/_utils.so -> r2/lib/utils
copying build/lib.linux-x86_64-2.7/r2/lib/utils/comment_tree_utils.so -> r2/lib/utils
copying build/lib.linux-x86_64-2.7/r2/lib/mr_tools/_mr_tools.so -> r2/lib/mr_tools
copying build/lib.linux-x86_64-2.7/r2/lib/db/_sorts.so -> r2/lib/db
copying build/lib.linux-x86_64-2.7/Cfilters.so -> 
# remove mangled output symlinks, similar to above.
rm -f /home/reddit/reddit/r2/build/public/static/https-tester.js
python r2/lib/js.py build_module "https-tester"
Compiling https-tester.js...Traceback (most recent call last):
  File "r2/lib/js.py", line 809, in <module>
    commands[sys.argv[1]](*sys.argv[2:])
  File "r2/lib/js.py", line 773, in wrapped
    fn(*args)
  File "r2/lib/js.py", line 805, in build_module
    module[name].build(minifier)
  File "r2/lib/js.py", line 182, in build
    minifier.compile(source, out)
  File "r2/lib/js.py", line 55, in compile
    stdout=dest,
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
make: *** [/home/reddit/reddit/r2/build/public/static/https-tester.js] Error 1
reddit@reddit:~/reddit/r2$ exit
```

**Comment by 13steinj** [comment]
Is the source repo also up to date with master?

Can you check the output of `echo $NODE_PATH` And of `uglifyjs`? The second, if there's no problem, should just hang indefinitely (Yes, I know that sounds strange but if it's the issue I'm thinking of it will crash and burn immediately).

Also have you tried to run `make clean && make all`?

**Comment by rsd** [comment]
> Is the source repo also up to date with master?
Yes.  for what I can see it has not been updated for some months now.

> Can you check the output of echo $NODE_PATH And of uglifyjs? The second, if there's no problem, should just hang indefinitely (Yes, I know that sounds strange but if it's the issue I'm thinking of it will crash and burn immediately).
/usr/lib/nodejs:/usr/lib/node_modules:/usr/share/javascript
uglify does no hang, it takes less than 1s to go back to prompt.  Should it read from STDIN?

> Also have you tried to run make clean && make all?
Yep

**Comment by 13steinj** [comment]
In my experience uglifyjs with no arguments attempts to read from stdin but then hangs instead. However sometimes (evidently not the problem in this case) the uglify binary fails and errors due to NODE_PATH not being properly updated by /etc/profile (in fact that's one of the issues plaguing the Travis builds right now).

Even though the repo hasn't been updated in months sometimes commits are added in from ages ago, and if your source repo was cloned before then you might be missing something-- a git fetch and diff can't hurt.  Also I noticed that the repo is directly in your home directory; whereas the install script usually installs it in ~/src/[reddit|i18n|websockets|activity], that may be one issue. You may want to try rerunning the install script after configuring it to match your set up, or wipe clean and rerun it entirely.

**Comment by rsd** [comment]
I will post the complete install procedure in a fresh install.

Just some clarifications:
- Each install was preceded with a git clone, so it is updated every time.
- I am cloning inside reddit's home, the the repository is /home/reddit/reddit.  Is this what you call "directly in the home directory" or should I move /home/reddit/reddit to /home/reddit ?
- The profile matches the environment:
```
reddit@reddit:~/reddit/r2$ cat /etc/profile.d/nodejs.sh 

NODE_PATH=/usr/lib/nodejs:/usr/lib/node_modules:/usr/share/javascript
export NODE_PATH

reddit@reddit:~/reddit/r2$ echo $NODE_PATH
/usr/lib/nodejs:/usr/lib/node_modules:/usr/share/javascript
```
- Are you sure of this: "install script usually installs it in ~/src/[reddit|i18n|websockets|activity]" ?  I have not seen any attempt to create a src directory in the home folder or repository, but it might be because I did not get into this tage yet.

**Comment by rsd** [comment]
I think it works now.  Thanks.
However, I get this warning (not sure how important it is):
`Cannot find Baseplate. Skipping Thrift build.`

They are installed from the repository (manually compiling them giver the same warning):
```
reddit@reddit:~/reddit/r2$ dpkg -l | grep basep
ii  python-baseplate                     0.21.0                                     amd64        convenient service framework (Python 2)
reddit@reddit:~/reddit/r2$ dpkg -l | grep thrift
ii  fbthrift-compiler                    0.31.0-0reddit6                            amd64        code generator/compiler for Thrift definitions
ii  python-fbthrift                      0.31.0-0reddit6                            amd64        Python library for Thrift
```

This is how it worked on a clean system (trusty):
```
sudo add-apt-repository ppa:reddit/ppa
sudo add-apt-repository ppa:fkrull/deadsnakes-python2.7
sudo apt-get update
sudo apt-get dist-upgrade
sudo apt-get install haproxy stunnel python-setuptools python-dev libmemcached-dev libpq-dev libxml2-dev libxslt1-dev python-imaging git-core gcc optipng jpegoptim postgresql-client make gettext nodejs  node-uglify g++ python-snappy git node-less cython python-baseplate python-l2cs python-pip
sudo easy_install pip
sudo pip install -U setuptools

#logout and login again

git clone https://github.com/reddit/reddit.git
cd reddit/r2
python setup.py build
sudo python setup.py develop
make
```
