### ISSUE TITLE
/domain/foo.com/new?sort=rising shows /r/all/new

### ISSUE THREAD

**Issue by sparr** [reddit/reddit#377]
I am viewing http://reddit.com/domain/twitter.com/ and all is well. Then I click the "new" tab and I go to http://reddit.com/domain/twitter.com/new and I start seeing posts from all subreddits. Switching my "new" view from "rising" to "new" fixes the problem temporarily and by default, but going to http://reddit.com/domain/twitter.com/new?sort=rising still yields the incorrect behavior.

screenshot: http://i.imgur.com/Evw0m.png

**Comment by akkatracker** [comment]
@kjoconnor Just going through old issues and it seems this one's been fixed. Issue can be safely closed

**Comment by kjoconnor** [comment]
Thanks for the update @akkatracker!
