### ISSUE TITLE
Defective middle-click behavior in Chrome on Reddit

### ISSUE THREAD

**Issue by Galphanore** [reddit/reddit#731]
On reddit when using Chrome if I middle click something on reddit it opens a new tab *in the same process as the first tab*. If, instead, I right-click and click "Open in a new tab" it behaves correctly and opens it *in a new process*. I noticed, however, that this does not happen when the page is in read-only mode nor when I am not logged in. So, something that is changed when logged in is causing this bug. This does not happen on any other website I frequent.

The main problem with this is that nesting multiple reddit tabs under a single process causes memory issues. Multiple times a day my "reddit" process will grow to over a gigabyte of memory and freeze/crash. The memory cleanup in Chrome is handled much more smoothly when a page allows it to spawn child processes. [This page](http://dev.chromium.org/developers/design-documents/process-models) explains the process model and may help resolve this issue.

Further information : This issue only occurs if you have "open links in a new window" enabled.

**Comment by JordanMilne** [comment]
Tested on Chrome Linux, doesn't appear to be the case anymore. [The addition of a `rel="noreferrer"` attribute](https://github.com/reddit/reddit/commit/29777e10f48680b3bff4f8105401f5348fc1bff0) when the "open links in a new window" preference is on fixed it.
