### ISSUE TITLE
Link becomes "visited" upon button-down instead of button-up

### ISSUE THREAD

**Issue by shkg** [reddit/reddit#78]
This is the use case:

* You are opening multiple links on a page by middle-clicking
* Some links fail to open because the browser received the button-up event of the click outside the link hit-box (this is a normal behavior among all Browsers I know: Firefox, Chrome, IE...)

Actual result: 
Reddit shows the unvisited link as "visited"

Expected result: 
Reddit should not change the status of the link unless it was visited

**Comment by spladug** [comment]
fixed in ad42be6
