### ISSUE TITLE
Infinite scrolling the messages inbox page results in display defects

### ISSUE THREAD

**Issue by chromakode** [reddit/reddit#807]
"False" is displayed at the bottom of message boxes, and markdown is displayed without space compression disabled.

**Comment by JordanMilne** [comment]
The strange `False` was fixed by cfd3a1cf1ac565c417267c1cbc296c1784032ec4 and it looks like the markdown goes through `safemarkdown()` which will wrap the output in `<!-- SC_OFF -->[...]<!-- SC_ON -->`, is this still an issue?

**Comment by chromakode** [comment]
Looks fixed. Nice work!

**Comment by chromakode** [comment]
Spoke too soon. I still see space compression removing spaces around links in messages infinite-scrolled on https://www.reddit.com/message/inbox/.compact.

**Comment by JordanMilne** [comment]
Aha, I see what it is now, the response from the `.json-compact` endpoint isn't space compressed, it still contains the `SC_ON` and `SC_OFF` comments verbatim. But the listing gets run through `$.insert_things()` which will run the HTML through `$.unsafe()`. [`$.unsafe()` *also* does space compression for some reason](https://github.com/reddit/reddit/blob/master/r2/r2/public/static/js/compact.js#L35), but it doesn't respect the `SC_ON` and `SC_OFF` comments.

**Comment by JordanMilne** [comment]
All fixed by the above! :tada: 

Would have preferred spacecompressing `json-compact` and `json-html` responses before sending them out, but I'm sure someone is relying on them *not* being spacecompressed.

**Comment by chromakode** [comment]
Thank you!

![](http://gifsb.in/hat-tip/5ajbeWB.gif)
