### ISSUE TITLE
Chrome autofill does not work with username or password

### ISSUE THREAD

**Issue by dbb** [reddit/reddit#855]
Not much else I can say about it. Log in, then Chrome will ask if you want to save user/pass, confirm. 

Log out. Click on the username field, no suggestions. Manually type in correct username, and the password field stays blank.

I've tried this with the latest version of Chrome on Windows and Linux. It does not happen with any other websites that I'm aware of. Also, Firefox seems to handle these fields on reddit correctly. I believe midori does too, which leads me to believe that this isn't a webkit issue.

**Comment by ShankarGanesh** [comment]
Hi andre-d,

It seems to be happening still in Chrome and Remember me works for me in Firefox . Kindly update me what needs t be done for the above. Is there any changes we cane make to avoid this issue ?

Thanks,
Shankar.

**Comment by xiongchiamiov** [comment]
Step one would be figuring out why it isn't working in Chrome.  Then we can figure out if we want to (or can) fix it.

**Comment by KamranMackey** [comment]
This issue was created 2 years ago. No way in heck this issue still occurs. Because it works fine for me in Chrome 43.

**Comment by xiongchiamiov** [comment]
Excellent.
